START TRANSACTION;

DROP TABLE IF EXISTS `atomicSkills`;
CREATE TABLE `atomicSkills` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `text` text DEFAULT NULL,
  `additionalDescription` text DEFAULT NULL,
  `competencyId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=512 DEFAULT CHARSET=utf8;

INSERT INTO `atomicSkills` VALUES (1,'Базовые алгоритмы','Линейный поиск, сортировка и бинарный поиск, обход многомерного массива',1);
INSERT INTO `atomicSkills` VALUES (2,'Векторные и матричные операции','',1);
INSERT INTO `atomicSkills` VALUES (3,'Сложные типы данных','',1);
INSERT INTO `atomicSkills` VALUES (4,'Рекурсия','',1);
INSERT INTO `atomicSkills` VALUES (5,'Лямбда функции','',1);
INSERT INTO `atomicSkills` VALUES (6,'Карринг','',1);
INSERT INTO `atomicSkills` VALUES (7,'Функции высшего порядка','',1);
INSERT INTO `atomicSkills` VALUES (8,'Чистота функций','',1);
INSERT INTO `atomicSkills` VALUES (9,'Побочные эффекты функций','',1);
INSERT INTO `atomicSkills` VALUES (10,'Замыкания','',1);
INSERT INTO `atomicSkills` VALUES (11,'Понятие вычислимости','',1);
INSERT INTO `atomicSkills` VALUES (12,'Машина Тьюринга','',1);
INSERT INTO `atomicSkills` VALUES (13,'Конечные автоматы','',1);
INSERT INTO `atomicSkills` VALUES (14,'Классы вычислительной сложности','O(N), O(N*log(N)), O(N!), ..., P, FP, NP',1);
INSERT INTO `atomicSkills` VALUES (15,'NP-полнота','',1);
INSERT INTO `atomicSkills` VALUES (16,'Алгоритм NP-перебора','',1);
INSERT INTO `atomicSkills` VALUES (17,'Параллельные алгоритмы','Очередь, конвейер',1);
INSERT INTO `atomicSkills` VALUES (18,'Транзакции','',1);
INSERT INTO `atomicSkills` VALUES (19,'Мертвая блокировка','',1);
INSERT INTO `atomicSkills` VALUES (20,'Состояние гонки','',1);
INSERT INTO `atomicSkills` VALUES (21,'Семафоры','',1);
INSERT INTO `atomicSkills` VALUES (22,'Мьютексы','',1);
INSERT INTO `atomicSkills` VALUES (23,'Базовые понятия ООП','Абстракция, инкапсуляция, наследование, полиморфизм',2);
INSERT INTO `atomicSkills` VALUES (24,'Инкапсуляция данных','Приватные методы',2);
INSERT INTO `atomicSkills` VALUES (25,'Интерфейс','',2);
INSERT INTO `atomicSkills` VALUES (26,'Абстрактный класс','',2);
INSERT INTO `atomicSkills` VALUES (27,'Простые шаблоны проектирования','Одиночка (singleton), фабрика (factory), фасад (fascade), адаптер (adapter)',2);
INSERT INTO `atomicSkills` VALUES (28,'Расширение без наследования','Композиция, полиморфные классы, шаблонные методы',2);
INSERT INTO `atomicSkills` VALUES (29,'Сериализация объектов','И десериализация',2);
INSERT INTO `atomicSkills` VALUES (30,'Дополнительные шаблоны проектирования','Наблюдатель (observer), посетитель (visitor), стратегия (strategy), реестр (registry)',2);
INSERT INTO `atomicSkills` VALUES (31,'DI-фрейморки','',2);
INSERT INTO `atomicSkills` VALUES (32,'Архитектурные принципы ООП','SRP, OCP, LSP, ISP, DIP (SOLID), DRY, KISS, YAGNI',2);
INSERT INTO `atomicSkills` VALUES (33,'Архитектурные шаблоны','MVC, MVP, MVVM, DDD',2);
INSERT INTO `atomicSkills` VALUES (34,'Организация и оформление кода','По файлам, папкам, PSR-0, PSR-1, PSR-2, PSR-4',2);
INSERT INTO `atomicSkills` VALUES (35,'Понятное именование','Переменных, объектов, классов, функций, таблиц',3);
INSERT INTO `atomicSkills` VALUES (36,'Основные запахи кода','Дублирование кода, мертвый код, операторы switch, стрельба дробью, завистливые функции и пр.',3);
INSERT INTO `atomicSkills` VALUES (37,'Базовые техники рефакторинга','Извлечение/перемещение метода, класса, удаление посредника, инкапсуляция поля, замена параметров объектом, свертывание иерархии и пр.',3);
INSERT INTO `atomicSkills` VALUES (38,'Правило бойскаута','Оставь поляну лучше, чем она была до тебя',3);
INSERT INTO `atomicSkills` VALUES (39,'Переиспользуемый код','',3);
INSERT INTO `atomicSkills` VALUES (40,'Практики экстремального программирования','Парное программирование, заказчик всегда рядом, непрерывная интеграция, частые релизы и пр.',3);
INSERT INTO `atomicSkills` VALUES (41,'Комментирование и документирование','',3);
INSERT INTO `atomicSkills` VALUES (42,'Модульные тесты','',3);
INSERT INTO `atomicSkills` VALUES (43,'TDD/BDD','',3);
INSERT INTO `atomicSkills` VALUES (44,'Скорость через улучшение качества','',3);
INSERT INTO `atomicSkills` VALUES (45,'Ревизия кода','',3);
INSERT INTO `atomicSkills` VALUES (46,'Гибкость кода','',3);
INSERT INTO `atomicSkills` VALUES (47,'Частые запуски автотестов','',4);
INSERT INTO `atomicSkills` VALUES (48,'Разработка модульных тестов','',4);
INSERT INTO `atomicSkills` VALUES (49,'Cредства и фреймоврки тестирования PHP','PHPUnit, Atoum, Simpletest, Behat, Mink, Codeception, Mockery',4);
INSERT INTO `atomicSkills` VALUES (50,'Средства и фреймворки тестирования JavaScript','Jasmine, qunit, nightwatch, jest, chai, mocha, assert',4);
INSERT INTO `atomicSkills` VALUES (51,'Основные понятия тестирования','Тест-план, тест-дизайн, тест-анализ. Методы чёрного ящика, белого и серого ящика',4);
INSERT INTO `atomicSkills` VALUES (52,'Написание баг-репортов','',4);
INSERT INTO `atomicSkills` VALUES (53,'Классы эквивалентности','',4);
INSERT INTO `atomicSkills` VALUES (54,'Прочие виды тестирования','Интеграционное, системное, функциональное, регрессионное, приемочное и пр.',4);
INSERT INTO `atomicSkills` VALUES (55,'Средства автоматизации тестирования UI','Selenium, appium',4);
INSERT INTO `atomicSkills` VALUES (56,'Data-driven тестирование','',4);
INSERT INTO `atomicSkills` VALUES (57,'Методики автоматизированного тестирования','Keyword-driven, Behavior-driven, Model-based',4);
INSERT INTO `atomicSkills` VALUES (58,'Работа с менеджментом','',5);
INSERT INTO `atomicSkills` VALUES (59,'Инициативность в получении информации','',5);
INSERT INTO `atomicSkills` VALUES (60,'Анализ возможных вариантов решения','',5);
INSERT INTO `atomicSkills` VALUES (61,'Декомпозиция сложных задач','',5);
INSERT INTO `atomicSkills` VALUES (62,'Планирование последовательности задач и шагов','',5);
INSERT INTO `atomicSkills` VALUES (63,'Синтез общих решений','',5);
INSERT INTO `atomicSkills` VALUES (64,'Анализ технических факторов','',5);
INSERT INTO `atomicSkills` VALUES (65,'Анализ бизнес-факторов','',5);
INSERT INTO `atomicSkills` VALUES (66,'Анализ затрат','',5);
INSERT INTO `atomicSkills` VALUES (67,'Анализ рисков','',5);
INSERT INTO `atomicSkills` VALUES (68,'Выявление сути задачи','',5);
INSERT INTO `atomicSkills` VALUES (69,'Работа с экспертами предметной области','',5);
INSERT INTO `atomicSkills` VALUES (70,'Предложение альтернативных вариантов','',5);
INSERT INTO `atomicSkills` VALUES (71,'Клиент-серверная архитектура','',6);
INSERT INTO `atomicSkills` VALUES (72,'Основные понятия веб','HTML, CSS, DOM, Ajax',6);
INSERT INTO `atomicSkills` VALUES (73,'Основы JavaScript','',6);
INSERT INTO `atomicSkills` VALUES (74,'Способы хранения и передачи состояния','Cookie, сессия',6);
INSERT INTO `atomicSkills` VALUES (75,'Основы HTML5','',6);
INSERT INTO `atomicSkills` VALUES (76,'Основы CSS3','',6);
INSERT INTO `atomicSkills` VALUES (77,'Основы SQL','',6);
INSERT INTO `atomicSkills` VALUES (78,'API браузера','Window, Document, LocalStorage, History и др.',6);
INSERT INTO `atomicSkills` VALUES (79,'Архитектурный стиль REST','',6);
INSERT INTO `atomicSkills` VALUES (80,'Протокол HTTP','',6);
INSERT INTO `atomicSkills` VALUES (81,'Протокол SOAP','',6);
INSERT INTO `atomicSkills` VALUES (82,'RESTful веб-службы','',6);
INSERT INTO `atomicSkills` VALUES (83,'Формат передачи данных JSON','',6);
INSERT INTO `atomicSkills` VALUES (84,'Формат передачи данных XML','',6);
INSERT INTO `atomicSkills` VALUES (85,'CRUD','',6);
INSERT INTO `atomicSkills` VALUES (86,'Принципы работы кэширования и сжатия','Gzip-сжатие, заголовки Last-Modified, Etag, Expires, Cache-control',6);
INSERT INTO `atomicSkills` VALUES (87,'Основные заголовки HTTP','Content-Encoding, Content-Type, Referer, User-Agent',6);
INSERT INTO `atomicSkills` VALUES (88,'CORS','',6);
INSERT INTO `atomicSkills` VALUES (89,'HTTP-статусы','200, 300, 400, 500',6);
INSERT INTO `atomicSkills` VALUES (90,'Работа с клиентами базы данных','',7);
INSERT INTO `atomicSkills` VALUES (91,'Базовые SQL-запросы (DML)','SELECT, INSERT, UPDATE, DELETE',7);
INSERT INTO `atomicSkills` VALUES (92,'Расширенные SQL-запросы (DML)','JOIN, ORDER BY, GROUP BY, HAVING, подзапросы',7);
INSERT INTO `atomicSkills` VALUES (93,'Запросы на изменение схемы (DDL)','',7);
INSERT INTO `atomicSkills` VALUES (94,'Использование функций SQL','',7);
INSERT INTO `atomicSkills` VALUES (95,'Аггрегатные функции SQL','MAX, MIN, SUM, AVG, GROUP_CONCAT',7);
INSERT INTO `atomicSkills` VALUES (96,'Виды','',7);
INSERT INTO `atomicSkills` VALUES (97,'Индексы','',7);
INSERT INTO `atomicSkills` VALUES (98,'Транзакции','',7);
INSERT INTO `atomicSkills` VALUES (99,'Атомарные операции','',7);
INSERT INTO `atomicSkills` VALUES (100,'Переменные SQL','',7);
INSERT INTO `atomicSkills` VALUES (101,'Хранимые процедуры SQL','',7);
INSERT INTO `atomicSkills` VALUES (102,'Разработка собственных функций SQL','',7);
INSERT INTO `atomicSkills` VALUES (103,'Курсор','',7);
INSERT INTO `atomicSkills` VALUES (104,'Триггер','',7);
INSERT INTO `atomicSkills` VALUES (105,'NoSQL','',7);
INSERT INTO `atomicSkills` VALUES (106,'Хранилища ключ-значение','MemcacheDB, Beanstalk, Redis',7);
INSERT INTO `atomicSkills` VALUES (107,'Нормальные формы','6 штук + доменно-ключевая + Бойса-Кодда',7);
INSERT INTO `atomicSkills` VALUES (108,'Целенаправленная денормализация','',7);
INSERT INTO `atomicSkills` VALUES (109,'ACID','',7);
INSERT INTO `atomicSkills` VALUES (110,'Теорема CAP','',7);
INSERT INTO `atomicSkills` VALUES (111,'Реализации SQL','MySQL, PostgreSQL, MSSQL, Oracle',7);
INSERT INTO `atomicSkills` VALUES (112,'Оптимизирование настроект серверов','',7);
INSERT INTO `atomicSkills` VALUES (113,'Кластеризация и репликация данных','',7);
INSERT INTO `atomicSkills` VALUES (114,'Колоночные базы данных','Hbase, Cassandra',7);
INSERT INTO `atomicSkills` VALUES (115,'Документ-ориентированные базы данных','CouchDB, MongoDB',7);
INSERT INTO `atomicSkills` VALUES (116,'Графовые базы данных','InfiniteGraph, FlockDB',7);
INSERT INTO `atomicSkills` VALUES (117,'Недостатки интуитивного подхода к анализу','',8);
INSERT INTO `atomicSkills` VALUES (118,'Консультации с коллегами','',8);
INSERT INTO `atomicSkills` VALUES (119,'Визуальный анализ','',8);
INSERT INTO `atomicSkills` VALUES (120,'A/B тестирование','',8);
INSERT INTO `atomicSkills` VALUES (121,'Техники многомерного анализа','Факторный анализ, кластерный анализ',8);
INSERT INTO `atomicSkills` VALUES (122,'Использование ПО для анализа данных','Microsoft Analysis Services, Pentaho Mondrian',8);
INSERT INTO `atomicSkills` VALUES (123,'MDX','',8);
INSERT INTO `atomicSkills` VALUES (124,'Data Warehouse','',8);
INSERT INTO `atomicSkills` VALUES (125,'Основы статистического анализа','Размер и принципы формирования выборки, дисперсия, среднее, медиана, доверительный интервал, значимость, дисперсия, p-значение, стандартное отклонение',8);
INSERT INTO `atomicSkills` VALUES (126,'Основные распределения','Нормальное, Стьюдента',8);
INSERT INTO `atomicSkills` VALUES (127,'Специализированное ПО для статистического анализа','Statistica, Matlab, R, SPSS',8);
INSERT INTO `atomicSkills` VALUES (128,'Математическое моделирование','',8);
INSERT INTO `atomicSkills` VALUES (129,'Подключение библиотек при помощи тэга script','',9);
INSERT INTO `atomicSkills` VALUES (130,'jQuery, jQuery-UI','',9);
INSERT INTO `atomicSkills` VALUES (131,'Backbone.js','',9);
INSERT INTO `atomicSkills` VALUES (132,'Underscore.js/Lodash','',9);
INSERT INTO `atomicSkills` VALUES (133,'Универсальные фреймворки для верстки','Bootstrap, Foundation, Skeleton и пр.',9);
INSERT INTO `atomicSkills` VALUES (134,'SPA-фреймворки','Angular.js, Vue.js, Ember.js, Meteor.js, React.js/Redux, i-bem.js',9);
INSERT INTO `atomicSkills` VALUES (135,'Модули JavaScript','AMD, CommonJS, ES6',9);
INSERT INTO `atomicSkills` VALUES (136,'Модульный CSS','',9);
INSERT INTO `atomicSkills` VALUES (137,'Системы сборки','Browserify, Webpack, Parcel',9);
INSERT INTO `atomicSkills` VALUES (138,'Менеджеры пакетов','bower, npm, yarn',9);
INSERT INTO `atomicSkills` VALUES (139,'Системы запуска задач','Gulp.js, Grunt',9);
INSERT INTO `atomicSkills` VALUES (140,'Препроцессоры CSS','SASS/SCSS, LESS, PostCSS',9);
INSERT INTO `atomicSkills` VALUES (141,'Препроцессоры JS','Babel',9);
INSERT INTO `atomicSkills` VALUES (142,'Линтеры','JSLint, JSHint, ESLint',9);
INSERT INTO `atomicSkills` VALUES (143,'Минификаторы/обфускаторы кода','Uglify.js, Google Closure Compiler, JSMin',9);
INSERT INTO `atomicSkills` VALUES (144,'Оптимизаторы кода','Prepack',9);
INSERT INTO `atomicSkills` VALUES (145,'Архитектуры SPA','',9);
INSERT INTO `atomicSkills` VALUES (146,'Отладка JavaScipt кода','',9);
INSERT INTO `atomicSkills` VALUES (147,'TypeScript','',9);
INSERT INTO `atomicSkills` VALUES (148,'CoffeeScript','',9);
INSERT INTO `atomicSkills` VALUES (149,'Базовый синтаксис языка','Переменные, циклы, условия, функции, классы',10);
INSERT INTO `atomicSkills` VALUES (150,'Способы организации наследования','Модель конструктора, функциональная, прототипная, OLOO, ES6',10);
INSERT INTO `atomicSkills` VALUES (151,'Области видимости','Динамические, лексические',10);
INSERT INTO `atomicSkills` VALUES (152,'Контекст this','',10);
INSERT INTO `atomicSkills` VALUES (153,'Типизация в JavaScript','',10);
INSERT INTO `atomicSkills` VALUES (154,'Приведение к общему типу (coercion)','',10);
INSERT INTO `atomicSkills` VALUES (155,'Реализация асинхронности в JavaScript','',10);
INSERT INTO `atomicSkills` VALUES (156,'Promise','',10);
INSERT INTO `atomicSkills` VALUES (157,'Разработка на ванильном JS','',10);
INSERT INTO `atomicSkills` VALUES (158,'Оптимизация производительности','',10);
INSERT INTO `atomicSkills` VALUES (159,'Стандарт ES2015/ES6','',10);
INSERT INTO `atomicSkills` VALUES (160,'Стандарты ES6+','',10);
INSERT INTO `atomicSkills` VALUES (161,'Async/await','',10);
INSERT INTO `atomicSkills` VALUES (162,'Генераторы','',10);
INSERT INTO `atomicSkills` VALUES (163,'Реактивное программирование','rx, bacon, kefir',10);
INSERT INTO `atomicSkills` VALUES (164,'Перекрытие (shadowing) переменных','',10);
INSERT INTO `atomicSkills` VALUES (165,'Поднятие (hoisting) переменных','',10);
INSERT INTO `atomicSkills` VALUES (166,'Немедленно вызываемые функции (IIFE)','',10);
INSERT INTO `atomicSkills` VALUES (167,'Паттерны оптимизации','',10);
INSERT INTO `atomicSkills` VALUES (168,'Режим полного соответствия стандарту','',10);
INSERT INTO `atomicSkills` VALUES (169,'Глобальный объект','',10);
INSERT INTO `atomicSkills` VALUES (170,'Цепь областей видимости','',10);
INSERT INTO `atomicSkills` VALUES (171,'Цепь прототипов','',10);
INSERT INTO `atomicSkills` VALUES (172,'Стандартная библиотека (SPL)','',11);
INSERT INTO `atomicSkills` VALUES (173,'Основные расширения','mcrypt, xml, mbstring, gd, imagick, mysqli и пр.',11);
INSERT INTO `atomicSkills` VALUES (174,'Автозагрузка','',11);
INSERT INTO `atomicSkills` VALUES (175,'Composer','',11);
INSERT INTO `atomicSkills` VALUES (176,'Pear','',11);
INSERT INTO `atomicSkills` VALUES (177,'PSR-0','',11);
INSERT INTO `atomicSkills` VALUES (178,'PSR-4','',11);
INSERT INTO `atomicSkills` VALUES (179,'Разработка на фреймворках','Symfony 2/3, Laravel 4/5, Yii 1/2, Zend Framework 1/2 и пр.',11);
INSERT INTO `atomicSkills` VALUES (180,'Использование PDO','',11);
INSERT INTO `atomicSkills` VALUES (181,'Использование ORM','Propel, Eloquent, Doctrine',11);
INSERT INTO `atomicSkills` VALUES (182,'Работа с популярными библиотеками','Carbon, ImageWorkshop, Twig, Guzzle, Goutte, SwiftMailer, Mockery, библиотеки The PHP League',11);
INSERT INTO `atomicSkills` VALUES (183,'Отладка кода','IDE, Xdebug',11);
INSERT INTO `atomicSkills` VALUES (184,'Системы очередей','ZMQ, RabbitMQ, ActiveMQ, Amazon SQS',11);
INSERT INTO `atomicSkills` VALUES (185,'Поисковые системы','Apache Lucene, Apache Solr, Elasticsearch, Sphinx',11);
INSERT INTO `atomicSkills` VALUES (186,'Разработка монолитных приложений','',11);
INSERT INTO `atomicSkills` VALUES (187,'Разработка микросервисных приложений','',11);
INSERT INTO `atomicSkills` VALUES (188,'Авторизация и аутентификация','Протоколы OAuth 1/2, OpenID, JWT. Системы с ACL',11);
INSERT INTO `atomicSkills` VALUES (189,'Бэкенд разработка на других языках','JavaScript/NodeJS, Ruby',11);
INSERT INTO `atomicSkills` VALUES (190,'Фреймворки прочих языков','Express, Koa, Rails',11);
INSERT INTO `atomicSkills` VALUES (191,'Работа с высоконагруженными системами','',11);
INSERT INTO `atomicSkills` VALUES (192,'Работа с большими объемами данных','',11);
INSERT INTO `atomicSkills` VALUES (193,'Исправление багов в библиотеках, платформах','',11);
INSERT INTO `atomicSkills` VALUES (194,'Резервное копирование кода','',12);
INSERT INTO `atomicSkills` VALUES (195,'Основы систем контроля версий','Фиксация изменений, ветвления, отправка и получение данных',12);
INSERT INTO `atomicSkills` VALUES (196,'Прочие операции','Перемещение и слияние кода, изменение и удаление коммитов, работа с несколькими репозиториями',12);
INSERT INTO `atomicSkills` VALUES (197,'Способы совместной работы','Централизованная работа, feature branch, gitflow, forking workflow',12);
INSERT INTO `atomicSkills` VALUES (199,'Хуки','',12);
INSERT INTO `atomicSkills` VALUES (200,'Интеграция с внешними скриптами','',12);
INSERT INTO `atomicSkills` VALUES (201,'Ручная минификация и оптимизация файлов','',13);
INSERT INTO `atomicSkills` VALUES (202,'Конфигурирование системам сборки','Gulp, Grunt, Webpack',13);
INSERT INTO `atomicSkills` VALUES (203,'Многовходовая сборка','',13);
INSERT INTO `atomicSkills` VALUES (204,'Нестандартные кофигурации','',13);
INSERT INTO `atomicSkills` VALUES (205,'Сборка legacy-кода','',13);
INSERT INTO `atomicSkills` VALUES (206,'Объединение систем на нескольких фреймворках','',13);
INSERT INTO `atomicSkills` VALUES (207,'Работа с Linux на уровне пользователя','',14);
INSERT INTO `atomicSkills` VALUES (208,'Установка и удаление программ','',14);
INSERT INTO `atomicSkills` VALUES (209,'Подключение к сетям','',14);
INSERT INTO `atomicSkills` VALUES (210,'Консоль','',14);
INSERT INTO `atomicSkills` VALUES (211,'Консольные команды','',14);
INSERT INTO `atomicSkills` VALUES (212,'Скрипты','',14);
INSERT INTO `atomicSkills` VALUES (213,'Конфигурационные файлы/реестр','',14);
INSERT INTO `atomicSkills` VALUES (214,'Работа с драйверами и оборудованием','',14);
INSERT INTO `atomicSkills` VALUES (215,'Виртуализация','',14);
INSERT INTO `atomicSkills` VALUES (216,'Установка ОС','',14);
INSERT INTO `atomicSkills` VALUES (217,'Работа с ОС на уровне системного администрирования','',14);
INSERT INTO `atomicSkills` VALUES (218,'Установка и настройка серверных программ','',14);
INSERT INTO `atomicSkills` VALUES (219,'Организация сетевого взаимодействия','',14);
INSERT INTO `atomicSkills` VALUES (220,'Архитектура компьютера','',14);
INSERT INTO `atomicSkills` VALUES (221,'Сетевые коммуникационные протоколы','IPv4, IPv6, TCP, UDP, POP, IMAP, SMTP, HTTP, SMB',14);
INSERT INTO `atomicSkills` VALUES (222,'Веб-сервер','Apache, Nginx, lighthttpd',14);
INSERT INTO `atomicSkills` VALUES (223,'СУБД','MySQL, PostgreSQL',14);
INSERT INTO `atomicSkills` VALUES (224,'Системы управления конфигурациями','Puppet, Chef, Ansible, Salt',14);
INSERT INTO `atomicSkills` VALUES (225,'Контейнеризация','Vagrant, docker, docker-compose, kubernetes',14);
INSERT INTO `atomicSkills` VALUES (226,'SSH','',14);
INSERT INTO `atomicSkills` VALUES (227,'VPN','OpenVPN, pptpd',14);
INSERT INTO `atomicSkills` VALUES (228,'SSL','OpenSSL, Let“s Encrypt',14);
INSERT INTO `atomicSkills` VALUES (229,'Хостинг','',15);
INSERT INTO `atomicSkills` VALUES (230,'Amazon','',15);
INSERT INTO `atomicSkills` VALUES (231,'Digital Ocean','',15);
INSERT INTO `atomicSkills` VALUES (232,'Выгрузка при помощи FTP/SFTP','',15);
INSERT INTO `atomicSkills` VALUES (233,'Git','',15);
INSERT INTO `atomicSkills` VALUES (234,'Миграции БД','',15);
INSERT INTO `atomicSkills` VALUES (235,'Системы CI','Jenkins, TeamCity, Travis-CI, GitlabCI',15);
INSERT INTO `atomicSkills` VALUES (236,'Практики DevOps','ChatOps, IaS, Docker, пайплайны',15);
INSERT INTO `atomicSkills` VALUES (237,'Системы мониторинга','Prometheus, Zabbix',15);
INSERT INTO `atomicSkills` VALUES (238,'Kubernetes','',15);
INSERT INTO `atomicSkills` VALUES (239,'Инфраструктурная организация рефакторинга БД','',15);
INSERT INTO `atomicSkills` VALUES (240,'Использование для написания кода','',16);
INSERT INTO `atomicSkills` VALUES (241,'Установка и настройка расширений','',16);
INSERT INTO `atomicSkills` VALUES (242,'Настройка автокоррекции синтаксиса','',16);
INSERT INTO `atomicSkills` VALUES (243,'Функции рефакторинга кода','Переименование переменных, функций, классов',16);
INSERT INTO `atomicSkills` VALUES (244,'Работа с системой контроля версий','',16);
INSERT INTO `atomicSkills` VALUES (245,'Работа с базой данных','',16);
INSERT INTO `atomicSkills` VALUES (246,'Использование профилировщика','',16);
INSERT INTO `atomicSkills` VALUES (247,'Управляющие комбинации клавиш','',16);
INSERT INTO `atomicSkills` VALUES (248,'Разные IDE','IntelliJ IDEA, VS Code, Eclipse',16);
INSERT INTO `atomicSkills` VALUES (249,'Работа в одиночку','',17);
INSERT INTO `atomicSkills` VALUES (250,'Работа в кроссфункциональной команде','',17);
INSERT INTO `atomicSkills` VALUES (251,'Устранение конфликтов в коде при помощи VCS','',17);
INSERT INTO `atomicSkills` VALUES (252,'Поддержание общего домена знаний','Документирование, рассказ о наработках, ответы на вопросы',17);
INSERT INTO `atomicSkills` VALUES (253,'Парное программирование','',17);
INSERT INTO `atomicSkills` VALUES (254,'Разработка по каскадной методологии','',17);
INSERT INTO `atomicSkills` VALUES (255,'Гибкие методологии разработки','Scrum, kanban',17);
INSERT INTO `atomicSkills` VALUES (256,'Организация процесса разработки','',17);
INSERT INTO `atomicSkills` VALUES (257,'Работа без менеджеров','',17);
INSERT INTO `atomicSkills` VALUES (258,'Принятие решений по собственным ощущениям','',18);
INSERT INTO `atomicSkills` VALUES (259,'Использование данных и фактов для формирования решения','',18);
INSERT INTO `atomicSkills` VALUES (260,'Консультации с коллегами для принятия решения','',18);
INSERT INTO `atomicSkills` VALUES (261,'Навыки безопасной коммуникации','',18);
INSERT INTO `atomicSkills` VALUES (262,'Навыки активного слушания','',18);
INSERT INTO `atomicSkills` VALUES (263,'Использование поисковой системы для поиска решений','',19);
INSERT INTO `atomicSkills` VALUES (264,'Чтение технической литературы','',19);
INSERT INTO `atomicSkills` VALUES (265,'Понимание своих сильных и слабых сторон','',19);
INSERT INTO `atomicSkills` VALUES (266,'Обучение коллег','',19);
INSERT INTO `atomicSkills` VALUES (267,'Подготовка образовательных материалов','',19);
INSERT INTO `atomicSkills` VALUES (268,'Регулярное дистанционное обучение','',19);
INSERT INTO `atomicSkills` VALUES (269,'Регулярное очное обучение','',19);
INSERT INTO `atomicSkills` VALUES (270,'Написание технических статей или записей в блоге','',19);
INSERT INTO `atomicSkills` VALUES (271,'Участие в конференциях в качестве слушателя','',19);
INSERT INTO `atomicSkills` VALUES (272,'Участие в конференциях в качестве докладчика','',19);
INSERT INTO `atomicSkills` VALUES (273,'Поверхностная ревизия','По формальным критериям вроде именования, стилистики, местоположения файлов',20);
INSERT INTO `atomicSkills` VALUES (274,'Глубокая ревизия кода','По всем критериям, включая смысл кода, используемые алгоритмы, соответствие задаче, оптимальность алгоритма и архитектурную корректность',20);
INSERT INTO `atomicSkills` VALUES (275,'Позитивная обратная связь по коду','',20);
INSERT INTO `atomicSkills` VALUES (276,'Формирование предложений и идей','Чем больше идей, тем лучше',20);
INSERT INTO `atomicSkills` VALUES (277,'Ревизия кода в больших задачах','Когда кода много',20);
INSERT INTO `atomicSkills` VALUES (278,'Использование автоматизированных средств для ревизии','',20);
INSERT INTO `atomicSkills` VALUES (279,'Оценка по собственным ощущениям','',21);
INSERT INTO `atomicSkills` VALUES (280,'Оценка с поправочным коэффициентом','',21);
INSERT INTO `atomicSkills` VALUES (281,'Оценка сроков через сложность задачи','',21);
INSERT INTO `atomicSkills` VALUES (282,'Круговая/коллективная оценка','Покер планирования',21);
INSERT INTO `atomicSkills` VALUES (283,'Оценка вилкой по двум точкам','Минимум, максимум',21);
INSERT INTO `atomicSkills` VALUES (284,'Оценка вилкой с тремя точками','Минимум, максимум, наиболее вероятный срок',21);
INSERT INTO `atomicSkills` VALUES (285,'Скорость команды и диаграмма сгорания','',21);
INSERT INTO `atomicSkills` VALUES (286,'Работа с проектами с небольшим сроком жизни','',22);
INSERT INTO `atomicSkills` VALUES (287,'Переписывание проектов «с нуля»','',22);
INSERT INTO `atomicSkills` VALUES (288,'Предел технической сложности проекта','',22);
INSERT INTO `atomicSkills` VALUES (289,'Работа с техническим долгом','',22);
INSERT INTO `atomicSkills` VALUES (290,'Рефакторинг','',22);
INSERT INTO `atomicSkills` VALUES (291,'Работа с «хрупкими комками грязи»','Сложными проектами с хрупким кодом и большим legacy',22);
INSERT INTO `atomicSkills` VALUES (292,'Стабилизация скорости разработки проектов','',22);
INSERT INTO `atomicSkills` VALUES (293,'Изучение исходных текстов продуктов','',23);
INSERT INTO `atomicSkills` VALUES (294,'Изучение багтреккеров продуктов','',23);
INSERT INTO `atomicSkills` VALUES (295,'Оформление PRов к продуктам с открытым кодом','',23);
INSERT INTO `atomicSkills` VALUES (296,'Решение PRов, подготовка пулл-запросов','',23);
INSERT INTO `atomicSkills` VALUES (297,'Постоянная поддержка проекта с открытым кодом','',23);
INSERT INTO `atomicSkills` VALUES (298,'Участие в Open Source сообществах','',23);
INSERT INTO `atomicSkills` VALUES (299,'Знание иностранного языка на уровне чтения документации','Beginner, Elementary, Pre-Intermediate',24);
INSERT INTO `atomicSkills` VALUES (300,'Знание на уровне полноценного письменного общения','Intermediate, Upper-Intermediate',24);
INSERT INTO `atomicSkills` VALUES (301,'Понимание устной речи','',24);
INSERT INTO `atomicSkills` VALUES (302,'Поддержка разговоров на технические темы','',24);
INSERT INTO `atomicSkills` VALUES (303,'Поддержка разговоров на бытовые темы','',24);
INSERT INTO `atomicSkills` VALUES (304,'Деловая и техническая переписка','',24);
INSERT INTO `atomicSkills` VALUES (305,'Знание на уровне свободного владения языка','Advanced, Proficiency',24);
INSERT INTO `atomicSkills` VALUES (306,'Сертификация знаний иностранного языка','TOEFL, IELTS',24);
INSERT INTO `atomicSkills` VALUES (307,'Размещения, перестановки, сочетания','',27);
INSERT INTO `atomicSkills` VALUES (308,'Биномиальные коэффициенты','',27);
INSERT INTO `atomicSkills` VALUES (309,'Математическое ожидание','',27);
INSERT INTO `atomicSkills` VALUES (310,'Дисперсия','',27);
INSERT INTO `atomicSkills` VALUES (311,'Условная вероятность','',27);
INSERT INTO `atomicSkills` VALUES (312,'Основные распределения','Нормальное, биномиальное, Стьюдента, Пуассона, Трейси-Видома',27);
INSERT INTO `atomicSkills` VALUES (313,'Основные понятия','Тест-план, Тест-кейс, баг',28);
INSERT INTO `atomicSkills` VALUES (314,'Эффект пестицида','',28);
INSERT INTO `atomicSkills` VALUES (315,'Работа с багтреккером','',28);
INSERT INTO `atomicSkills` VALUES (316,'Работа с функциональными требованиями','',28);
INSERT INTO `atomicSkills` VALUES (317,'Классы эквивалентности','',28);
INSERT INTO `atomicSkills` VALUES (318,'Формирование разбиения области тестирования','',28);
INSERT INTO `atomicSkills` VALUES (319,'Анализ границ области тестирования','',28);
INSERT INTO `atomicSkills` VALUES (320,'Методики тестирования','Черный, белый и серый ящики',28);
INSERT INTO `atomicSkills` VALUES (321,'Виды тестирования','Компонентное, системное, интеграционное. Регрессионное, стресс, приёмочное',28);
INSERT INTO `atomicSkills` VALUES (322,'Построение тест-плана','',28);
INSERT INTO `atomicSkills` VALUES (323,'Построение тест-кейсов','',28);
INSERT INTO `atomicSkills` VALUES (324,'Причинно-следственные диаграммы','',28);
INSERT INTO `atomicSkills` VALUES (325,'Анализ модели состояния','',28);
INSERT INTO `atomicSkills` VALUES (326,'Оценка покрытия кода и требований тестами','Покрытие функций, условий, решений',28);
INSERT INTO `atomicSkills` VALUES (327,'Основные понятия веб-разработки','Веб-сервер, веб-клиент, POST-запросы, GET-запросы',28);
INSERT INTO `atomicSkills` VALUES (328,'Использование средств перехвата запросов','Fiddler',28);
INSERT INTO `atomicSkills` VALUES (329,'Протоколы веб','HTTP, JSON, FTP, telnet, SMTP, POP',28);
INSERT INTO `atomicSkills` VALUES (330,'Тестирование защищенности веб-приложений','',28);
INSERT INTO `atomicSkills` VALUES (331,'SQL-инъекции','',28);
INSERT INTO `atomicSkills` VALUES (332,'XSS','',28);
INSERT INTO `atomicSkills` VALUES (333,'Нагрузочное тестирование','JMeter, HP Load Runner, ab, siege',28);
INSERT INTO `atomicSkills` VALUES (334,'Сборка динамического покрытия кода тестами','',28);
INSERT INTO `atomicSkills` VALUES (335,'Знание языка программирования','Python, java, javascript, C#',29);
INSERT INTO `atomicSkills` VALUES (336,'Использование IDE','',29);
INSERT INTO `atomicSkills` VALUES (337,'Инструменты записи сценариев','',29);
INSERT INTO `atomicSkills` VALUES (338,'Инспекция кода','',29);
INSERT INTO `atomicSkills` VALUES (339,'Тест-дизайн','',29);
INSERT INTO `atomicSkills` VALUES (340,'Средства отладки в CLI и IDE','',29);
INSERT INTO `atomicSkills` VALUES (341,'Использование Selenium','или надстроек Appium, Winium, Windows Application Driver',29);
INSERT INTO `atomicSkills` VALUES (342,'Data Driven Testing','',29);
INSERT INTO `atomicSkills` VALUES (343,'Behaviour Driven Testing','',29);
INSERT INTO `atomicSkills` VALUES (344,'Model Driven Testing','',29);
INSERT INTO `atomicSkills` VALUES (345,'Keyword Driven Testing','',29);
INSERT INTO `atomicSkills` VALUES (346,'Шаблоны проектирования тестов','Functional, PageObjects',29);
INSERT INTO `atomicSkills` VALUES (347,'Распределенное тестирование','',29);
INSERT INTO `atomicSkills` VALUES (348,'Selenium Server','',29);
INSERT INTO `atomicSkills` VALUES (349,'Selenium Grid','',29);
INSERT INTO `atomicSkills` VALUES (350,'Облачные сервисы тестирования','',29);
INSERT INTO `atomicSkills` VALUES (351,'Встроенные типы переменных','',26);
INSERT INTO `atomicSkills` VALUES (352,'Mutable/immutable типы','',26);
INSERT INTO `atomicSkills` VALUES (353,'Динамическая типизация','',26);
INSERT INTO `atomicSkills` VALUES (354,'Базовый синтаксис языка','И инструкции управления потоком выполнения',26);
INSERT INTO `atomicSkills` VALUES (355,'Синтаксис функций','',26);
INSERT INTO `atomicSkills` VALUES (356,'Области видимости переменных','Правило LEGB',26);
INSERT INTO `atomicSkills` VALUES (357,'Итераторы','',26);
INSERT INTO `atomicSkills` VALUES (358,'Генераторы','',26);
INSERT INTO `atomicSkills` VALUES (359,'Документирование кода','В соответствии с PEP8',26);
INSERT INTO `atomicSkills` VALUES (360,'Средства функционального программирования','map, filter, reduce',26);
INSERT INTO `atomicSkills` VALUES (361,'Анонимные функции (lambda)','',26);
INSERT INTO `atomicSkills` VALUES (362,'Использование инструкции yield','',26);
INSERT INTO `atomicSkills` VALUES (363,'Проектирование модулей','',26);
INSERT INTO `atomicSkills` VALUES (364,'Работа с модулями','Повторная загрузка, относительный импорт, сокрытие данных',26);
INSERT INTO `atomicSkills` VALUES (365,'Классы, создание и использование','',26);
INSERT INTO `atomicSkills` VALUES (366,'Наследование и переопределение методов','',26);
INSERT INTO `atomicSkills` VALUES (367,'Композиция и делегирование для классов','',26);
INSERT INTO `atomicSkills` VALUES (368,'Перегрузка операторов','',26);
INSERT INTO `atomicSkills` VALUES (369,'Фабрики объектов','',26);
INSERT INTO `atomicSkills` VALUES (370,'Классы \"старого\" и \"нового\" стилей','',26);
INSERT INTO `atomicSkills` VALUES (371,'Создание и использование исключений','',26);
INSERT INTO `atomicSkills` VALUES (372,'Создание и использование контекстных менеджеров','',26);
INSERT INTO `atomicSkills` VALUES (373,'Объекты unicode, bytes, bytearray','',26);
INSERT INTO `atomicSkills` VALUES (374,'Env-сборки','При помощи утилиты pip',26);
INSERT INTO `atomicSkills` VALUES (375,'Консольный отладчик python','',26);
INSERT INTO `atomicSkills` VALUES (376,'Декораторы функций','',26);
INSERT INTO `atomicSkills` VALUES (377,'Декораторы классов','',26);
INSERT INTO `atomicSkills` VALUES (378,'Дескрипторы','',26);
INSERT INTO `atomicSkills` VALUES (379,'Множественное наследование','',26);
INSERT INTO `atomicSkills` VALUES (380,'Различные варианты python','cpython, ironpython, jpython, Stackless Python',26);
INSERT INTO `atomicSkills` VALUES (381,'Разработка с веб-фреймворками','Django, Flask, Pyramid',26);
INSERT INTO `atomicSkills` VALUES (382,'Разработка с GUI-фреймворками','PyQt, Tkinter, WxPython',26);
INSERT INTO `atomicSkills` VALUES (383,'Метапрограммирование','',26);
INSERT INTO `atomicSkills` VALUES (384,'Сетевое программирование','',26);
INSERT INTO `atomicSkills` VALUES (385,'Асинхронное программирование','',26);
INSERT INTO `atomicSkills` VALUES (386,'Мультипроцессное программирование','',26);
INSERT INTO `atomicSkills` VALUES (387,'Мультипоточное программирование','',26);
INSERT INTO `atomicSkills` VALUES (388,'Специализированные библиотеки','NumPy, SciPy, SQLAlchemy',26);
INSERT INTO `atomicSkills` VALUES (389,'«Великодушный пожизненный диктатор»','',26);
INSERT INTO `atomicSkills` VALUES (390,'CVS',NULL,12);
INSERT INTO `atomicSkills` VALUES (391,'SVN',NULL,12);
INSERT INTO `atomicSkills` VALUES (392,'Git',NULL,12);
INSERT INTO `atomicSkills` VALUES (393,'Mercurial',NULL,12);
INSERT INTO `atomicSkills` VALUES (394,'Fossil',NULL,12);
INSERT INTO `atomicSkills` VALUES (395,'Понимание принципов дизайна','',30);
INSERT INTO `atomicSkills` VALUES (396,'Базовый дизайн','Самостоятельно набросать что-то',30);
INSERT INTO `atomicSkills` VALUES (397,'Совместная работа с дизайнерами','Качественный результат вне зависимости от уровня дизайнера',30);
INSERT INTO `atomicSkills` VALUES (398,'Программирование','',31);
INSERT INTO `atomicSkills` VALUES (399,'Базовые понятия','Цикл, ветвление',31);
INSERT INTO `atomicSkills` VALUES (400,'Основы верстки','HTML, CSS',31);
INSERT INTO `atomicSkills` VALUES (401,'Знание языков программирования','Python, Ruby, PHP, JavaScript, Java, C#',31);
INSERT INTO `atomicSkills` VALUES (402,'Совместная работа с программистами','',31);
INSERT INTO `atomicSkills` VALUES (403,'Основы архитектуры ПО','',31);
INSERT INTO `atomicSkills` VALUES (404,'Выбор технологического стека','',31);
INSERT INTO `atomicSkills` VALUES (405,'Ревизия кода','',31);
INSERT INTO `atomicSkills` VALUES (406,'Рефакторинг кода','',31);
INSERT INTO `atomicSkills` VALUES (407,'Ручное тестирование','',32);
INSERT INTO `atomicSkills` VALUES (408,'Совместная работа с тестировщиками','',32);
INSERT INTO `atomicSkills` VALUES (409,'Организация процесса тестирования','',32);
INSERT INTO `atomicSkills` VALUES (410,'Работа с договорами контрагентов','Понимание условий, фиксация договоренностей в дополнительных соглашениях',33);
INSERT INTO `atomicSkills` VALUES (411,'Совместная работа с юристами компании','',33);
INSERT INTO `atomicSkills` VALUES (412,'Основы гражданского права','',33);
INSERT INTO `atomicSkills` VALUES (413,'Основы трудового права','',33);
INSERT INTO `atomicSkills` VALUES (414,'Работа с трудовыми и гражданско-правовыми договорами','',33);
INSERT INTO `atomicSkills` VALUES (415,'Основы документооборота','Договор, счет, акт',34);
INSERT INTO `atomicSkills` VALUES (416,'Основы бухучета','Бухгалтерский баланс, отчетность, системы налогообложения',34);
INSERT INTO `atomicSkills` VALUES (417,'Основы кадрового учета','Зарплата, отпуски, отгулы, справки по болезни',34);
INSERT INTO `atomicSkills` VALUES (418,'Совместная работа с бухгалтерами компании','',34);
INSERT INTO `atomicSkills` VALUES (419,'Умение не опаздывать','',35);
INSERT INTO `atomicSkills` VALUES (420,'Тайм-менеджмент','Выполнение задач в срок, организация рабочего процесса',35);
INSERT INTO `atomicSkills` VALUES (421,'Методология GTD','',35);
INSERT INTO `atomicSkills` VALUES (422,'Делегирование задач','И отслеживание их выполнения',36);
INSERT INTO `atomicSkills` VALUES (423,'Методы принятия решений','',37);
INSERT INTO `atomicSkills` VALUES (424,'Модель теории очередей','',37);
INSERT INTO `atomicSkills` VALUES (425,'Модели управления запасами','',37);
INSERT INTO `atomicSkills` VALUES (426,'Модель линейного программирования','',37);
INSERT INTO `atomicSkills` VALUES (427,'Экономический анализ','',37);
INSERT INTO `atomicSkills` VALUES (428,'Анализ временных рядов','',37);
INSERT INTO `atomicSkills` VALUES (429,'Качественные методы','Экспертная оценка, модель ожиданий',37);
INSERT INTO `atomicSkills` VALUES (430,'Фасилитация собраний','',37);
INSERT INTO `atomicSkills` VALUES (431,'Основы теории игр','',37);
INSERT INTO `atomicSkills` VALUES (432,'5S','',53);
INSERT INTO `atomicSkills` VALUES (433,'JIT','',53);
INSERT INTO `atomicSkills` VALUES (434,'ISO 9000','',53);
INSERT INTO `atomicSkills` VALUES (435,'Шесть сигма','',53);
INSERT INTO `atomicSkills` VALUES (436,'TQM','',53);
INSERT INTO `atomicSkills` VALUES (437,'Кайдзен','',53);
INSERT INTO `atomicSkills` VALUES (438,'QFD','',53);
INSERT INTO `atomicSkills` VALUES (439,'Уклонение от рисков','Отказ от ненадежных партнеров, проектов. Страхование',46);
INSERT INTO `atomicSkills` VALUES (440,'Локализация рисков','Договора о совместной деятельности, создание подразделений',46);
INSERT INTO `atomicSkills` VALUES (441,'Диверсификация рисков','Распределение ответственности, ресурсов',46);
INSERT INTO `atomicSkills` VALUES (442,'Компенсация рисков','Прогнозирование, мониторинг, создание резервов',46);
INSERT INTO `atomicSkills` VALUES (443,'Теория ограничений','Барабан-буфер-веревка',54);
INSERT INTO `atomicSkills` VALUES (444,'Циклы организационного управления','PDCA/PDSA/SDCA (Деминга-Шухарта)',54);
INSERT INTO `atomicSkills` VALUES (445,'Управление на основе данных','',54);
INSERT INTO `atomicSkills` VALUES (446,'Техники ведения переговоров','',38);
INSERT INTO `atomicSkills` VALUES (447,'Продажи','',38);
INSERT INTO `atomicSkills` VALUES (448,'Работа с недовольными клиентами','',38);
INSERT INTO `atomicSkills` VALUES (449,'Работа с возражениями','',38);
INSERT INTO `atomicSkills` VALUES (450,'Отслеживание регламента встречи','Время, тема, вопросы',39);
INSERT INTO `atomicSkills` VALUES (451,'Модерация, медиация','',39);
INSERT INTO `atomicSkills` VALUES (452,'Управление группой','Знакомство, роли, открытие, работа, закрытие. Работа ведущим',39);
INSERT INTO `atomicSkills` VALUES (453,'Управление конфликтами','',39);
INSERT INTO `atomicSkills` VALUES (454,'Подготовка переговорных','',39);
INSERT INTO `atomicSkills` VALUES (455,'Подготовка печатных материалов','',39);
INSERT INTO `atomicSkills` VALUES (456,'Протоколирование встречи, фиксация договоренностей','',39);
INSERT INTO `atomicSkills` VALUES (457,'Педагогические основы менеджмента','Мотивация, подготовка, развитие',39);
INSERT INTO `atomicSkills` VALUES (458,'Основные процессы','Разработка дизайна, программирование, тестирование, эксплуатация',40);
INSERT INTO `atomicSkills` VALUES (459,'Группы процессов','Инициация, планирование, исполнение, контроль, закрытие',40);
INSERT INTO `atomicSkills` VALUES (460,'Взаимодействие процессов','',40);
INSERT INTO `atomicSkills` VALUES (461,'Жизненный цикл и фазы проекта','',40);
INSERT INTO `atomicSkills` VALUES (462,'PMBoK','',40);
INSERT INTO `atomicSkills` VALUES (463,'Водопад','',55);
INSERT INTO `atomicSkills` VALUES (464,'Scrum','',55);
INSERT INTO `atomicSkills` VALUES (465,'Канбан','',55);
INSERT INTO `atomicSkills` VALUES (466,'Бережливое производство (Lean)','',55);
INSERT INTO `atomicSkills` VALUES (467,'Prince2','',55);
INSERT INTO `atomicSkills` VALUES (468,'FFF','',55);
INSERT INTO `atomicSkills` VALUES (469,'Обязанности и вознаграждение','Аппеляция к договору, соблюдение полноты работ',41);
INSERT INTO `atomicSkills` VALUES (470,'Выбор подрядчиков','',41);
INSERT INTO `atomicSkills` VALUES (471,'Поиск компромиссных решений','',41);
INSERT INTO `atomicSkills` VALUES (472,'Понимание рисков и проблем подрядчика','',41);
INSERT INTO `atomicSkills` VALUES (473,'Позитивная и продуктивная коммуникация','',41);
INSERT INTO `atomicSkills` VALUES (474,'Оценка объема работ','',42);
INSERT INTO `atomicSkills` VALUES (475,'Оценка стоимости работ','',42);
INSERT INTO `atomicSkills` VALUES (476,'Оценка необходимых ресурсов','',42);
INSERT INTO `atomicSkills` VALUES (477,'Оценка возможностей клиента','',42);
INSERT INTO `atomicSkills` VALUES (478,'Оценка скорости выполнения работ','',42);
INSERT INTO `atomicSkills` VALUES (479,'Оформление коммерческих предложений','',42);
INSERT INTO `atomicSkills` VALUES (480,'Управление содержанием','',43);
INSERT INTO `atomicSkills` VALUES (481,'Управление расписанием','',43);
INSERT INTO `atomicSkills` VALUES (482,'Управление стоимостью','',43);
INSERT INTO `atomicSkills` VALUES (483,'Управление коммуникациями','',43);
INSERT INTO `atomicSkills` VALUES (484,'Управление ресурсами','',43);
INSERT INTO `atomicSkills` VALUES (485,'Управление закупками','',43);
INSERT INTO `atomicSkills` VALUES (486,'Управление заинтересованными сторонами','',43);
INSERT INTO `atomicSkills` VALUES (487,'Границы планирования','Когда план полезен, а когда - вреден',43);
INSERT INTO `atomicSkills` VALUES (488,'Урегулирование конфликтов','Компромисс, консенсус, переговоры',44);
INSERT INTO `atomicSkills` VALUES (489,'Мотивация','Внутренняя, внешняя, денежная, неденежная, теории X, Y и Z',44);
INSERT INTO `atomicSkills` VALUES (490,'Оценка команды','Оценка компетенций, KPI, 360 градусов, матричный метод',44);
INSERT INTO `atomicSkills` VALUES (491,'Развитие команды','Составление стратегии обучения, подбор индивидуальных и групповых занятий',44);
INSERT INTO `atomicSkills` VALUES (492,'Развитие личным примером','',44);
INSERT INTO `atomicSkills` VALUES (493,'Метод радикальной откровенности (radical candor)','',44);
INSERT INTO `atomicSkills` VALUES (494,'Эмпатия','И умение слушать',44);
INSERT INTO `atomicSkills` VALUES (495,'Взаимное доверие','',44);
INSERT INTO `atomicSkills` VALUES (496,'Дизайн-мышление','',45);
INSERT INTO `atomicSkills` VALUES (497,'Аналитическое мышление','',45);
INSERT INTO `atomicSkills` VALUES (498,'Сторителлинг','',45);
INSERT INTO `atomicSkills` VALUES (499,'Приоритезация задач','',51);
INSERT INTO `atomicSkills` VALUES (500,'Описание задач','',51);
INSERT INTO `atomicSkills` VALUES (501,'Отслеживание задач','',51);
INSERT INTO `atomicSkills` VALUES (502,'Оценка задач','',51);
INSERT INTO `atomicSkills` VALUES (503,'Проведение ретроспективы','',51);
INSERT INTO `atomicSkills` VALUES (504,'Проведение уточняющих встреч','Refinement meeting',51);
INSERT INTO `atomicSkills` VALUES (505,'Проведение ежедневных стендапов','',51);
INSERT INTO `atomicSkills` VALUES (506,'Проведение презентации задач на старте','',51);
INSERT INTO `atomicSkills` VALUES (507,'Проведение демонстрации результатов при окончании','',51);
INSERT INTO `atomicSkills` VALUES (508,'Работа с обратной связью стейкхолдеров','',51);
INSERT INTO `atomicSkills` VALUES (509,'Бэклог задач','',51);
INSERT INTO `atomicSkills` VALUES (510,'Диаграмма сгорания','',51);
INSERT INTO `atomicSkills` VALUES (511,'Работа с Windows на уровне пользователя','',14);

ALTER TABLE `competencies` CHANGE COLUMN `level1` `level1` text DEFAULT NULL;
ALTER TABLE `competencies` CHANGE COLUMN `level2` `level2` text DEFAULT NULL;
ALTER TABLE `competencies` CHANGE COLUMN `level3` `level3` text DEFAULT NULL;
ALTER TABLE `competencies` CHANGE COLUMN `level4` `level4` text DEFAULT NULL;

UPDATE `competencies` SET `code`='pmSelfDiscipline', `name`='Личная дисциплина' WHERE `id`='35';
UPDATE `competencies` SET `name`='Ведение встреч' WHERE `id`='39';
UPDATE `competencies` SET `name`='Планирование и управление' WHERE `id`='43';
UPDATE `competencies` SET `code`='pmTeamWork', `name`='Работа с командой' WHERE `id`='44';
UPDATE `competencies` SET `name`='Работа с продуктом' WHERE `id`='45';
UPDATE `competencies` SET `name`='Управление рисками' WHERE `id`='46';
UPDATE `competencies` SET `name`='Итерации и ритуалы гибких методологий' WHERE `id`='51';
INSERT INTO `competencies` VALUES (53,'pmQuality','Управление качеством',NULL,NULL,NULL,NULL,13);
INSERT INTO `competencies` VALUES (54,'pmOrgManagement','Управление организацией',NULL,NULL,NULL,NULL,13);
INSERT INTO `competencies` VALUES (55,'pmProjectMethods','Методологии ведения проектов',NULL,NULL,NULL,NULL,13);

INSERT INTO `competencyProfession` VALUES (56,26,2);

DROP TABLE IF EXISTS `courseVisits`;
CREATE TABLE `courseVisits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dateVisited` datetime NOT NULL DEFAULT current_timestamp(),
  `courseId` int(11) DEFAULT NULL,
  `userId` int(11) DEFAULT NULL,
  `sessionId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `courseId` (`courseId`),
  KEY `userId` (`userId`),
  KEY `sessionId` (`sessionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `courses` MODIFY `code` VARCHAR(60) DEFAULT NULL;
ALTER TABLE `courses` CHANGE COLUMN `url` `url` text DEFAULT NULL;
ALTER TABLE `courses` ADD COLUMN `eduProviderId` INT DEFAULT NULL NULL AFTER id;
ALTER TABLE `courses` ADD COLUMN `externalId` VARCHAR(36) DEFAULT NULL NULL AFTER id;
ALTER TABLE `courses` ADD COLUMN `description` TEXT NULL DEFAULT NULL AFTER `name`;
ALTER TABLE `courses` ADD COLUMN `modeOfStudy` VARCHAR(20) DEFAULT NULL NULL;
ALTER TABLE `courses` ADD COLUMN `courseForm` VARCHAR(20) DEFAULT NULL NULL;
ALTER TABLE `courses` ADD COLUMN `schedule` VARCHAR(20) DEFAULT NULL NULL;
ALTER TABLE `courses` ADD COLUMN `certificate` INT(1) DEFAULT 0 NOT NULL;
ALTER TABLE `courses` ADD COLUMN `tasksType` VARCHAR(20) DEFAULT NULL  NULL;
ALTER TABLE `courses` ADD COLUMN `lengthDays` INT DEFAULT 0 NULL;

LOCK TABLES `courses` WRITE;
/*!40000 ALTER TABLE `courses` DISABLE KEYS */;
TRUNCATE TABLE `courses`;
INSERT INTO `courses` VALUES (1,NULL,2,'html-verstka','HTML-верстка: с нуля до первого макета',NULL,'https://netology.ru/programs/html-verstka',23900.00,6,16,'online','webinar','evening',1,'teacherCheck',42);
INSERT INTO `courses` VALUES (2,NULL,2,'html-javascript','JavaScript в браузере: создаем интерактивные веб-страницы',NULL,'https://netology.ru/programs/html-javascript',20900.00,8,18,'online','webinar','evening',1,'teacherCheck',56);
INSERT INTO `courses` VALUES (3,NULL,2,'adaptive-mobile-layout','Адаптивная и мобильная верстка',NULL,'https://netology.ru/programs/adaptive-mobile-layout',20900.00,4,10,'online','webinar','evening',1,'teacherCheck',28);
INSERT INTO `courses` VALUES (4,NULL,2,'html-css-base','HTML и CSS с нуля',NULL,'https://netology.ru/programs/html-css-base',0.00,6,7,'online','webinar','evening',1,'teacherCheck',42);
INSERT INTO `courses` VALUES (5,NULL,2,'javascript','JavaScript: основы и современныe возможности языка',NULL,'https://netology.ru/programs/javascript',20900.00,9,18,'online','webinar','evening',1,'teacherCheck',63);
INSERT INTO `courses` VALUES (6,NULL,2,'php-sql','PHP/SQL: back-end разработка и базы данных',NULL,'https://netology.ru/programs/php-sql',20900.00,9,19,'online','webinar','evening',1,'teacherCheck',63);
INSERT INTO `courses` VALUES (7,NULL,2,'python-base','Python: программирование на каждый день и сверхбыстрое прототипирование',NULL,'https://netology.ru/programs/python-base',20900.00,13,26,'online','webinar','evening',1,'teacherCheck',91);
INSERT INTO `courses` VALUES (8,NULL,2,'react','Библиотека React: построй свою любовь к интерактивным веб-интерфейсам',NULL,'https://netology.ru/programs/react',20900.00,6,13,'online','webinar','evening',1,'teacherCheck',42);
INSERT INTO `courses` VALUES (9,NULL,2,'node','Node, AngularJS и MongoDB: разработка полноценных веб-приложений',NULL,'https://netology.ru/programs/node',20900.00,10,20,'online','webinar','evening',1,'teacherCheck',70);
INSERT INTO `courses` VALUES (12,NULL,3,'head-of-development','Руководитель разработки',NULL,'https://otus.ru/lessons/rukovoditel-razrabotki/',26000.00,4,32,'online','webinar','evening',1,'teacherCheck',28);
INSERT INTO `courses` VALUES (13,NULL,7,'it-english','Английский для IT-специалистов',NULL,'https://geekbrains.ru/courses/98',1098.00,2,10,'online','video','evening',1,'teacherCheck',14);
INSERT INTO `courses` VALUES (15,'6375',1,'centre-for-integrable-systems-introduction-to-python','Centre for Integrable Systems - Introduction to Python','Python','https://stepik.org/course/6375',NULL,0,NULL,'selfStudy','video','free',0,'autoCheck',0);
INSERT INTO `courses` VALUES (16,'6075',1,'it-intensiv-python','IT-интенсив (Python)','Интенсивный вводный курс в программирование на языке Python учащий эффективно решать задачи из реальной жизни. \n\nСтуденты курса получат фундаментальные знания о том, как компьютеры хранят и оперируют данными на примере проектов различной сложности: от простых консольных игр до настоящих автоматизированных решений. ','https://stepik.org/course/6075',NULL,0,NULL,'selfStudy','video','free',0,'autoCheck',0);
INSERT INTO `courses` VALUES (17,'512',1,'python-osnovy-i-primenenie','Python: основы и применение','Курс посвящен базовым принципам языка Python и программирования в целом. Он хорошо подойдет тем, кто уже может писать простейшие программы на Python или тем, кто до этого программировал на других языках.','https://stepik.org/course/512',NULL,0,NULL,'selfStudy','video','free',1,'autoCheck',1);
INSERT INTO `courses` VALUES (18,'431',1,'adaptivnyj-trenazher-python','Адаптивный тренажер Python','Курс представляет собой набор задач на языке Python. Сложность задач варьируется от начальной до высокой. Курс проходится в специальном адаптивном режиме!','https://stepik.org/course/431',NULL,0,NULL,'selfStudy','video','free',1,'autoCheck',1);
INSERT INTO `courses` VALUES (19,'154',1,'web-tehnologii','Web-технологии','Курс посвящен разработке серверной части web-приложений, их архитектуре и протоколу HTTP. По итогам курса вы научитесь: разрабатывать приложения на языке python, использовать MVC фреймворки, изучите верстку HTML страниц, погрузитесь в тематику web разработки и сможете выбирать конкретные технологии.','https://stepik.org/course/154',NULL,0,NULL,'selfStudy','video','free',1,'autoCheck',2);
INSERT INTO `courses` VALUES (20,'67',1,'programmirovanie-na-python','Программирование на Python','Курс посвящен базовым понятиям и элементам языка программирования Python (операторы, числовые и строковые переменные, списки, условия и циклы). Курс является вводным и наиболее подойдет слушателям, не имеющим опыта написания программ ни на одном из языков программирования.','https://stepik.org/course/67',NULL,0,NULL,'selfStudy','video','free',1,'autoCheck',1);
INSERT INTO `courses` VALUES (21,'4138',1,'git','GIT','','https://stepik.org/course/4138',NULL,0,NULL,'selfStudy','video','free',0,'autoCheck',0);
INSERT INTO `courses` VALUES (22,'3145',1,'osnovy-git','Основы Git','Курс описывает наиболее часто используемые  команды git, взятые из опыта реальных проектов.','https://stepik.org/course/3145',NULL,0,NULL,'selfStudy','video','free',1,'autoCheck',0);
INSERT INTO `courses` VALUES (23,'3203',1,'pogruzhenie-v-subd-sezon-2017','Погружение в СУБД. Сезон 2017.','Курс для тех, кто уже имеет некоторый опыт проектирования баз данных и разработки приложений и хочет расширить свои знания.','https://stepik.org/course/3203',NULL,0,NULL,'online','video','free',1,'autoCheck',2);
INSERT INTO `courses` VALUES (24,'2614',1,'bazy-dannyh','Базы данных','Курс знакомит слушателей с основными принципами работы со структурированными данными в реляционной модели, учит проектировать данные, описывать объекты базы данных в терминах реальной СУБД, составлять запросы на языке SQL, использовать представления, процедуры, функции и триггеры, создавать индексы, управлять конкурентным доступом к данным и манипулировать механизмом транзакций','https://stepik.org/course/2614',NULL,0,NULL,'selfStudy','video','free',1,'autoCheck',0);
INSERT INTO `courses` VALUES (25,'2586',1,'vvedenie-v-nerelyacionnye-bazy-dannyh','Введение в нереляционные базы данных','Данный курс посвящен практическим вопросам использования нереляционных СУБД. Его основной задачей является освоение  языков запросов наиболее популярных NoSQL решений и формирование представления о том в каких случаях лучше всего использовать тот или иной продукт. ','https://stepik.org/course/2586',NULL,0,NULL,'online','video','free',0,'autoCheck',0);
INSERT INTO `courses` VALUES (26,'551',1,'vvedenie-v-bazy-dannyh','Введение в базы данных','Знакомство с методами структурированного хранения данных, основами SQL, принципами использования баз данных в приложениях, обзор нереляционных способов хранения данных','https://stepik.org/course/551',NULL,0,NULL,'selfStudy','video','free',1,'autoCheck',1);
INSERT INTO `courses` VALUES (27,'2223',1,'javascript-dlya-nachinayuschih','JavaScript для начинающих','В данном курсе рассмотрены основы программирования на JavaScript а также некоторые инструменты и модели данных, необходимые для практического использования JavaScript.','https://stepik.org/course/2223',NULL,0,NULL,'selfStudy','video','free',0,'autoCheck',0);
INSERT INTO `courses` VALUES (28,'76',1,'osnovy-statistiki','Основы статистики','Курс знакомит слушателей с основными понятиями и методами математической статистики. В течение трех недель мы рассмотрим наиболее широко используемые статистические методы и принципы, стоящие за ними. Полученных знаний будет достаточно для решения широкого круга задач, возникающих в рамках исследовательской работы.','https://stepik.org/course/76',NULL,0,NULL,'selfStudy','video','free',1,'autoCheck',0);
INSERT INTO `courses` VALUES (29,'2621',1,'html-css-dlya-novichkov','Html, CSS для новичков','Курс направлен на изучение ОСНОВ HTML, CSS для новичков, начинающих и людей не знакомых с этим, но взявших путь освоить. Материал составлен учителем информатики и успешно применяется на уроках в школе.\nДля людей знающих HTML - уроки не расскажут о новом и покажутся поверхностными. ','https://stepik.org/course/2621',NULL,0,NULL,'selfStudy','video','free',0,'autoCheck',0);
INSERT INTO `courses` VALUES (30,'2376',1,'osnovy-upravleniya-proektami','Основы управления проектами','В настоящем курсе рассматриваются широко используемые методы проектного управления для проектов любых отраслей деятельности. Излагаемые в курсе методы являются базовыми для управления проектами.','https://stepik.org/course/2376',NULL,0,NULL,'selfStudy','video','free',0,'autoCheck',0);
INSERT INTO `courses` VALUES (31,'1128',1,'postanovka-zadachi-na-razrabotku-po','Постановка задачи на разработку ПО','Курс формирует базовые навыки подготовки и документирования требований к программному обеспечению. По итогам курса вы научитесь: работать с требованиями  и заинтересованными сторонами, анализировать проблему и формулировать требования, проектировать взаимодействие пользователей с системой, обеспечивать необходимые качества системы на этапе постановки задачи.','https://stepik.org/course/1128',NULL,0,NULL,'selfStudy','video','free',1,'autoCheck',1);
/*!40000 ALTER TABLE `courses` ENABLE KEYS */;
UNLOCK TABLES;

DROP TABLE IF EXISTS `coursesRequirements`;
CREATE TABLE `coursesRequirements` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `courseId` int(11) NOT NULL,
  `atomicSkillId` int(11) NOT NULL,
  `level` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `courseId` (`courseId`),
  KEY `atomicSkillId` (`atomicSkillId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `coursesRequirements` VALUES (1,16,71,'knowledge');
INSERT INTO `coursesRequirements` VALUES (2,16,72,'knowledge');
INSERT INTO `coursesRequirements` VALUES (3,16,75,'knowledge');
INSERT INTO `coursesRequirements` VALUES (4,16,79,'knowledge');
INSERT INTO `coursesRequirements` VALUES (5,16,80,'knowledge');
INSERT INTO `coursesRequirements` VALUES (6,16,83,'knowledge');
INSERT INTO `coursesRequirements` VALUES (7,16,90,'knowledge');
INSERT INTO `coursesRequirements` VALUES (8,16,105,'knowledge');
INSERT INTO `coursesRequirements` VALUES (9,17,351,'knowledge');
INSERT INTO `coursesRequirements` VALUES (10,17,354,'knowledge');
INSERT INTO `coursesRequirements` VALUES (11,17,355,'knowledge');
INSERT INTO `coursesRequirements` VALUES (12,17,365,'knowledge');
INSERT INTO `coursesRequirements` VALUES (13,18,351,'knowledge');
INSERT INTO `coursesRequirements` VALUES (14,18,354,'knowledge');
INSERT INTO `coursesRequirements` VALUES (15,18,355,'knowledge');
INSERT INTO `coursesRequirements` VALUES (16,18,365,'knowledge');
INSERT INTO `coursesRequirements` VALUES (17,18,356,'knowledge');
INSERT INTO `coursesRequirements` VALUES (18,18,357,'knowledge');
INSERT INTO `coursesRequirements` VALUES (19,18,358,'knowledge');
INSERT INTO `coursesRequirements` VALUES (20,18,359,'knowledge');
INSERT INTO `coursesRequirements` VALUES (21,18,366,'knowledge');
INSERT INTO `coursesRequirements` VALUES (22,18,364,'knowledge');
INSERT INTO `coursesRequirements` VALUES (23,18,361,'knowledge');
INSERT INTO `coursesRequirements` VALUES (24,19,351,'knowledge');
INSERT INTO `coursesRequirements` VALUES (25,19,354,'knowledge');
INSERT INTO `coursesRequirements` VALUES (26,19,355,'knowledge');
INSERT INTO `coursesRequirements` VALUES (27,19,365,'knowledge');
INSERT INTO `coursesRequirements` VALUES (28,19,356,'knowledge');
INSERT INTO `coursesRequirements` VALUES (29,19,207,'ability');
INSERT INTO `coursesRequirements` VALUES (30,19,210,'skill');
INSERT INTO `coursesRequirements` VALUES (31,19,211,'skill');
INSERT INTO `coursesRequirements` VALUES (32,19,195,'skill');
INSERT INTO `coursesRequirements` VALUES (33,19,392,'knowledge');
INSERT INTO `coursesRequirements` VALUES (34,22,210,'skill');
INSERT INTO `coursesRequirements` VALUES (35,22,211,'skill');
INSERT INTO `coursesRequirements` VALUES (36,23,90,'knowledge');
INSERT INTO `coursesRequirements` VALUES (37,23,91,'knowledge');
INSERT INTO `coursesRequirements` VALUES (38,23,93,'knowledge');
INSERT INTO `coursesRequirements` VALUES (39,23,354,'knowledge');
INSERT INTO `coursesRequirements` VALUES (40,24,1,'knowledge');
INSERT INTO `coursesRequirements` VALUES (41,24,125,'knowledge');
INSERT INTO `coursesRequirements` VALUES (42,24,2,'knowledge');
INSERT INTO `coursesRequirements` VALUES (43,25,210,'knowledge');
INSERT INTO `coursesRequirements` VALUES (44,25,211,'knowledge');
INSERT INTO `coursesRequirements` VALUES (45,26,210,'knowledge');
INSERT INTO `coursesRequirements` VALUES (46,26,211,'knowledge');
INSERT INTO `coursesRequirements` VALUES (47,26,90,'knowledge');
INSERT INTO `coursesRequirements` VALUES (48,22,207,'skill');
INSERT INTO `coursesRequirements` VALUES (49,25,207,'knowledge');
INSERT INTO `coursesRequirements` VALUES (50,26,207,'knowledge');
INSERT INTO `coursesRequirements` VALUES (51,31,511,'skill');

DROP TABLE IF EXISTS `coursesSkills`;
CREATE TABLE `coursesSkills` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `courseId` int(11) NOT NULL,
  `atomicSkillId` int(11) NOT NULL,
  `level` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `courseId` (`courseId`),
  KEY `atomicSkillId` (`atomicSkillId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `coursesSkills` VALUES (1,15,354,'knowledge');
INSERT INTO `coursesSkills` VALUES (2,15,355,'knowledge');
INSERT INTO `coursesSkills` VALUES (3,15,361,'knowledge');
INSERT INTO `coursesSkills` VALUES (4,15,365,'knowledge');
INSERT INTO `coursesSkills` VALUES (5,16,354,'knowledge');
INSERT INTO `coursesSkills` VALUES (6,16,355,'knowledge');
INSERT INTO `coursesSkills` VALUES (7,16,365,'knowledge');
INSERT INTO `coursesSkills` VALUES (8,16,71,'knowledge');
INSERT INTO `coursesSkills` VALUES (9,16,72,'knowledge');
INSERT INTO `coursesSkills` VALUES (10,16,90,'knowledge');
INSERT INTO `coursesSkills` VALUES (11,16,105,'knowledge');
INSERT INTO `coursesSkills` VALUES (12,17,365,'knowledge');
INSERT INTO `coursesSkills` VALUES (13,17,356,'knowledge');
INSERT INTO `coursesSkills` VALUES (14,17,357,'knowledge');
INSERT INTO `coursesSkills` VALUES (15,17,358,'knowledge');
INSERT INTO `coursesSkills` VALUES (16,17,359,'knowledge');
INSERT INTO `coursesSkills` VALUES (17,17,366,'knowledge');
INSERT INTO `coursesSkills` VALUES (18,17,364,'knowledge');
INSERT INTO `coursesSkills` VALUES (19,17,361,'knowledge');
INSERT INTO `coursesSkills` VALUES (20,17,71,'knowledge');
INSERT INTO `coursesSkills` VALUES (21,17,80,'knowledge');
INSERT INTO `coursesSkills` VALUES (22,17,72,'knowledge');
INSERT INTO `coursesSkills` VALUES (23,17,83,'knowledge');
INSERT INTO `coursesSkills` VALUES (24,17,84,'knowledge');
INSERT INTO `coursesSkills` VALUES (25,17,79,'knowledge');
INSERT INTO `coursesSkills` VALUES (26,17,82,'knowledge');
INSERT INTO `coursesSkills` VALUES (27,18,351,'skill');
INSERT INTO `coursesSkills` VALUES (28,18,354,'skill');
INSERT INTO `coursesSkills` VALUES (29,18,355,'skill');
INSERT INTO `coursesSkills` VALUES (30,18,365,'skill');
INSERT INTO `coursesSkills` VALUES (31,18,356,'skill');
INSERT INTO `coursesSkills` VALUES (32,18,1,'skill');
INSERT INTO `coursesSkills` VALUES (33,19,71,'knowledge');
INSERT INTO `coursesSkills` VALUES (34,19,72,'knowledge');
INSERT INTO `coursesSkills` VALUES (35,19,74,'knowledge');
INSERT INTO `coursesSkills` VALUES (36,19,75,'knowledge');
INSERT INTO `coursesSkills` VALUES (37,19,76,'knowledge');
INSERT INTO `coursesSkills` VALUES (38,19,80,'knowledge');
INSERT INTO `coursesSkills` VALUES (39,19,381,'knowledge');
INSERT INTO `coursesSkills` VALUES (40,19,222,'knowledge');
INSERT INTO `coursesSkills` VALUES (41,19,223,'knowledge');
INSERT INTO `coursesSkills` VALUES (42,20,354,'knowledge');
INSERT INTO `coursesSkills` VALUES (43,20,351,'knowledge');
INSERT INTO `coursesSkills` VALUES (44,20,380,'knowledge');
INSERT INTO `coursesSkills` VALUES (45,20,388,'knowledge');
INSERT INTO `coursesSkills` VALUES (46,20,355,'knowledge');
INSERT INTO `coursesSkills` VALUES (47,20,356,'knowledge');
INSERT INTO `coursesSkills` VALUES (48,20,364,'knowledge');
INSERT INTO `coursesSkills` VALUES (49,21,195,'knowledge');
INSERT INTO `coursesSkills` VALUES (50,21,392,'knowledge');
INSERT INTO `coursesSkills` VALUES (51,22,195,'knowledge');
INSERT INTO `coursesSkills` VALUES (52,22,392,'knowledge');
INSERT INTO `coursesSkills` VALUES (53,23,90,'skill');
INSERT INTO `coursesSkills` VALUES (54,23,92,'knowledge');
INSERT INTO `coursesSkills` VALUES (55,23,94,'knowledge');
INSERT INTO `coursesSkills` VALUES (56,23,95,'knowledge');
INSERT INTO `coursesSkills` VALUES (57,23,96,'knowledge');
INSERT INTO `coursesSkills` VALUES (58,23,97,'knowledge');
INSERT INTO `coursesSkills` VALUES (59,23,98,'knowledge');
INSERT INTO `coursesSkills` VALUES (60,23,99,'knowledge');
INSERT INTO `coursesSkills` VALUES (61,23,103,'knowledge');
INSERT INTO `coursesSkills` VALUES (62,23,106,'knowledge');
INSERT INTO `coursesSkills` VALUES (63,23,107,'knowledge');
INSERT INTO `coursesSkills` VALUES (64,23,109,'knowledge');
INSERT INTO `coursesSkills` VALUES (65,23,105,'knowledge');
INSERT INTO `coursesSkills` VALUES (66,24,90,'knowledge');
INSERT INTO `coursesSkills` VALUES (67,24,91,'knowledge');
INSERT INTO `coursesSkills` VALUES (68,24,92,'knowledge');
INSERT INTO `coursesSkills` VALUES (69,24,93,'knowledge');
INSERT INTO `coursesSkills` VALUES (70,24,94,'knowledge');
INSERT INTO `coursesSkills` VALUES (71,24,96,'knowledge');
INSERT INTO `coursesSkills` VALUES (72,24,97,'knowledge');
INSERT INTO `coursesSkills` VALUES (73,24,104,'knowledge');
INSERT INTO `coursesSkills` VALUES (74,24,101,'knowledge');
INSERT INTO `coursesSkills` VALUES (75,24,107,'knowledge');
INSERT INTO `coursesSkills` VALUES (76,25,223,'knowledge');
INSERT INTO `coursesSkills` VALUES (77,25,105,'knowledge');
INSERT INTO `coursesSkills` VALUES (78,26,92,'knowledge');
INSERT INTO `coursesSkills` VALUES (79,26,105,'knowledge');
INSERT INTO `coursesSkills` VALUES (80,26,106,'knowledge');
INSERT INTO `coursesSkills` VALUES (81,26,104,'knowledge');
INSERT INTO `coursesSkills` VALUES (82,26,101,'knowledge');
INSERT INTO `coursesSkills` VALUES (83,26,93,'knowledge');
INSERT INTO `coursesSkills` VALUES (84,26,107,'knowledge');
INSERT INTO `coursesSkills` VALUES (85,26,97,'skill');
INSERT INTO `coursesSkills` VALUES (86,27,149,'knowledge');
INSERT INTO `coursesSkills` VALUES (87,27,157,'knowledge');
INSERT INTO `coursesSkills` VALUES (88,27,153,'knowledge');
INSERT INTO `coursesSkills` VALUES (89,28,126,'knowledge');
INSERT INTO `coursesSkills` VALUES (90,28,121,'knowledge');
INSERT INTO `coursesSkills` VALUES (91,28,119,'knowledge');
INSERT INTO `coursesSkills` VALUES (92,28,125,'knowledge');
INSERT INTO `coursesSkills` VALUES (93,29,75,'knowledge');
INSERT INTO `coursesSkills` VALUES (94,29,76,'knowledge');
INSERT INTO `coursesSkills` VALUES (95,29,72,'knowledge');
INSERT INTO `coursesSkills` VALUES (96,29,73,'knowledge');
INSERT INTO `coursesSkills` VALUES (97,30,461,'knowledge');
INSERT INTO `coursesSkills` VALUES (98,30,462,'knowledge');
INSERT INTO `coursesSkills` VALUES (99,30,484,'knowledge');
INSERT INTO `coursesSkills` VALUES (100,30,459,'knowledge');
INSERT INTO `coursesSkills` VALUES (101,31,403,'knowledge');
INSERT INTO `coursesSkills` VALUES (102,31,497,'knowledge');
INSERT INTO `coursesSkills` VALUES (103,31,499,'knowledge');
INSERT INTO `coursesSkills` VALUES (104,31,500,'knowledge');
INSERT INTO `coursesSkills` VALUES (105,31,501,'knowledge');

DROP TABLE IF EXISTS `eduProviders`;
CREATE TABLE `eduProviders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(25) DEFAULT NULL,
  `name` varchar(150) DEFAULT NULL,
  `url` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `eduProviders` VALUES (1,'stepik','Stepik','http://welcome.stepik.org/ru');
INSERT INTO `eduProviders` VALUES (2,'netology','Нетология','https://netology.ru/');
INSERT INTO `eduProviders` VALUES (3,'otus','Otus','https://otus.ru/');
INSERT INTO `eduProviders` VALUES (4,'hexlet','Hexlet','https://ru.hexlet.io/');
INSERT INTO `eduProviders` VALUES (5,'coursera','Coursera','https://www.coursera.org/');
INSERT INTO `eduProviders` VALUES (6,'udemy','Udemy','https://www.udemy.com/');
INSERT INTO `eduProviders` VALUES (7,'geekbrains','GeekBrains','https://geekbrains.ru/');
INSERT INTO `eduProviders` VALUES (8,'moscoding','Moscow Coding School','https://moscoding.ru/');
INSERT INTO `eduProviders` VALUES (9,'intuit','Intuit','http://www.intuit.ru/');
INSERT INTO `eduProviders` VALUES (10,'htmlacademy','HtmlAcademy','https://htmlacademy.ru/');
INSERT INTO `eduProviders` VALUES (11,'lektorium','Лекториум','https://www.lektorium.tv/');
INSERT INTO `eduProviders` VALUES (12,'openedu','Открытое образование','https://openedu.ru/');
INSERT INTO `eduProviders` VALUES (13,'javarush','JavaRush','https://javarush.ru/');
INSERT INTO `eduProviders` VALUES (14,'newprolab','New Professions Lab','http://newprolab.com/ru/');
INSERT INTO `eduProviders` VALUES (15,'tceh','#tceh','http://tceh.com/edu/');
INSERT INTO `eduProviders` VALUES (16,'skillfactory','SkillFactory','http://skillfactory.ru/');

ALTER TABLE `polls` ADD COLUMN `sessionId` VARCHAR(36) DEFAULT NULL AFTER `userId`;

DROP TABLE IF EXISTS `sessions`;
CREATE TABLE `sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) DEFAULT NULL,
  `dateCreated` datetime NOT NULL DEFAULT current_timestamp(),
  `userId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `userId` (`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `sessionsSkills`;
CREATE TABLE `sessionsSkills` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sessionId` int(11) DEFAULT NULL,
  `atomicSkillId` int(11) DEFAULT NULL,
  `level` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sessionId` (`sessionId`),
  KEY `atomicSkillId` (`atomicSkillId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `users`
  ADD COLUMN `uuid` VARCHAR(36) NULL AFTER `id`,
  ADD UNIQUE INDEX `uuid` (`uuid` ASC);

COMMIT;