UPDATE `competencies` SET `code`='pmSelfDiscipline', `name`='Личная дисциплина' WHERE `id`='35';
UPDATE `competencies` SET `name`='Управление рисками' WHERE `id`='46';
UPDATE `competencies` SET `name`='Ведение встреч' WHERE `id`='39';
UPDATE `competencies` SET `name`='Планирование и управление' WHERE `id`='43';
UPDATE `competencies` SET `code`='pmTeamWork', `name`='Работа с командой' WHERE `id`='44';
UPDATE `competencies` SET `name`='Работа с продуктом' WHERE `id`='45';
UPDATE `competencies` SET `name`='Итерации и ритуалы гибких методологий' WHERE `id`='51';
INSERT INTO `competencies` (`id`, `code`, `name`, `competencyGroupId`) VALUES ('53', 'pmQuality', 'Управление качеством', '13');
INSERT INTO `competencies` (`id`, `code`, `name`, `competencyGroupId`) VALUES ('54', 'pmOrgManagement', 'Управление организацией', '13');
INSERT INTO `competencies` (`id`, `code`, `name`, `competencyGroupId`) VALUES ('55', 'pmProjectMethods', 'Методологии ведения проектов', '13');

CREATE TABLE `atomicSkills` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `text` text DEFAULT NULL,
  `additionalDescription` text DEFAULT NULL,
  `competencyId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `atomicSkills` VALUES (1,'Базовые алгоритмы','Линейный поиск, сортировка и бинарный поиск, обход многомерного массива',1);
INSERT INTO `atomicSkills` VALUES (2,'Векторные и матричные операции','',1);
INSERT INTO `atomicSkills` VALUES (3,'Сложные типы данных','',1);
INSERT INTO `atomicSkills` VALUES (4,'Рекурсия','',1);
INSERT INTO `atomicSkills` VALUES (5,'Лямбда функции','',1);
INSERT INTO `atomicSkills` VALUES (6,'Карринг','',1);
INSERT INTO `atomicSkills` VALUES (7,'Функции высшего порядка','',1);
INSERT INTO `atomicSkills` VALUES (8,'Чистота функций','',1);
INSERT INTO `atomicSkills` VALUES (9,'Побочные эффекты функций','',1);
INSERT INTO `atomicSkills` VALUES (10,'Замыкания','',1);
INSERT INTO `atomicSkills` VALUES (11,'Понятие вычислимости','',1);
INSERT INTO `atomicSkills` VALUES (12,'Машина Тьюринга','',1);
INSERT INTO `atomicSkills` VALUES (13,'Конечные автоматы','',1);
INSERT INTO `atomicSkills` VALUES (14,'Классы вычислительной сложности','O(N), O(N*log(N)), O(N!), ..., P, FP, NP',1);
INSERT INTO `atomicSkills` VALUES (15,'NP-полнота','',1);
INSERT INTO `atomicSkills` VALUES (16,'Алгоритм NP-перебора','',1);
INSERT INTO `atomicSkills` VALUES (17,'Параллельные алгоритмы','Очередь, конвейер',1);
INSERT INTO `atomicSkills` VALUES (18,'Транзакции','',1);
INSERT INTO `atomicSkills` VALUES (19,'Мертвая блокировка','',1);
INSERT INTO `atomicSkills` VALUES (20,'Состояние гонки','',1);
INSERT INTO `atomicSkills` VALUES (21,'Семафоры','',1);
INSERT INTO `atomicSkills` VALUES (22,'Мьютексы','',1);
INSERT INTO `atomicSkills` VALUES (23,'Базовые понятия ООП','Абстракция, инкапсуляция, наследование, полиморфизм',2);
INSERT INTO `atomicSkills` VALUES (24,'Инкапсуляция данных','Приватные методы',2);
INSERT INTO `atomicSkills` VALUES (25,'Интерфейс','',2);
INSERT INTO `atomicSkills` VALUES (26,'Абстрактный класс','',2);
INSERT INTO `atomicSkills` VALUES (27,'Простые шаблоны проектирования','Одиночка (singleton), фабрика (factory), фасад (fascade), адаптер (adapter)',2);
INSERT INTO `atomicSkills` VALUES (28,'Расширение без наследования','Композиция, полиморфные классы, шаблонные методы',2);
INSERT INTO `atomicSkills` VALUES (29,'Сериализация объектов','И десериализация',2);
INSERT INTO `atomicSkills` VALUES (30,'Дополнительные шаблоны проектирования','Наблюдатель (observer), посетитель (visitor), стратегия (strategy), реестр (registry)',2);
INSERT INTO `atomicSkills` VALUES (31,'DI-фрейморки','',2);
INSERT INTO `atomicSkills` VALUES (32,'Архитектурные принципы ООП','SRP, OCP, LSP, ISP, DIP (SOLID), DRY, KISS, YAGNI',2);
INSERT INTO `atomicSkills` VALUES (33,'Архитектурные шаблоны','MVC, MVP, MVVM, DDD',2);
INSERT INTO `atomicSkills` VALUES (34,'Организация и оформление кода','По файлам, папкам, PSR-0, PSR-1, PSR-2, PSR-4',2);
INSERT INTO `atomicSkills` VALUES (35,'Понятное именование','Переменных, объектов, классов, функций, таблиц',3);
INSERT INTO `atomicSkills` VALUES (36,'Основные запахи кода','Дублирование кода, мертвый код, операторы switch, стрельба дробью, завистливые функции и пр.',3);
INSERT INTO `atomicSkills` VALUES (37,'Базовые техники рефакторинга','Извлечение/перемещение метода, класса, удаление посредника, инкапсуляция поля, замена параметров объектом, свертывание иерархии и пр.',3);
INSERT INTO `atomicSkills` VALUES (38,'Правило бойскаута','Оставь поляну лучше, чем она была до тебя',3);
INSERT INTO `atomicSkills` VALUES (39,'Переиспользуемый код','',3);
INSERT INTO `atomicSkills` VALUES (40,'Практики экстремального программирования','Парное программирование, заказчик всегда рядом, непрерывная интеграция, частые релизы и пр.',3);
INSERT INTO `atomicSkills` VALUES (41,'Комментирование и документирование','',3);
INSERT INTO `atomicSkills` VALUES (42,'Модульные тесты','',3);
INSERT INTO `atomicSkills` VALUES (43,'TDD/BDD','',3);
INSERT INTO `atomicSkills` VALUES (44,'Скорость через улучшение качества','',3);
INSERT INTO `atomicSkills` VALUES (45,'Ревизия кода','',3);
INSERT INTO `atomicSkills` VALUES (46,'Гибкость кода','',3);
INSERT INTO `atomicSkills` VALUES (47,'Частые запуски автотестов','',4);
INSERT INTO `atomicSkills` VALUES (48,'Разработка модульных тестов','',4);
INSERT INTO `atomicSkills` VALUES (49,'Cредства и фреймоврки тестирования PHP','PHPUnit, Atoum, Simpletest, Behat, Mink, Codeception, Mockery',4);
INSERT INTO `atomicSkills` VALUES (50,'Средства и фреймворки тестирования JavaScript','Jasmine, qunit, nightwatch, jest, chai, mocha, assert',4);
INSERT INTO `atomicSkills` VALUES (51,'Основные понятия тестирования','Тест-план, тест-дизайн, тест-анализ. Методы чёрного ящика, белого и серого ящика',4);
INSERT INTO `atomicSkills` VALUES (52,'Написание баг-репортов','',4);
INSERT INTO `atomicSkills` VALUES (53,'Классы эквивалентности','',4);
INSERT INTO `atomicSkills` VALUES (54,'Прочие виды тестирования','Интеграционное, системное, функциональное, регрессионное, приемочное и пр.',4);
INSERT INTO `atomicSkills` VALUES (55,'Средства автоматизации тестирования UI','Selenium, appium',4);
INSERT INTO `atomicSkills` VALUES (56,'Data-driven тестирование','',4);
INSERT INTO `atomicSkills` VALUES (57,'Методики автоматизированного тестирования','Keyword-driven, Behavior-driven, Model-based',4);
INSERT INTO `atomicSkills` VALUES (58,'Работа с менеджментом','',5);
INSERT INTO `atomicSkills` VALUES (59,'Инициативность в получении информации','',5);
INSERT INTO `atomicSkills` VALUES (60,'Анализ возможных вариантов решения','',5);
INSERT INTO `atomicSkills` VALUES (61,'Декомпозиция сложных задач','',5);
INSERT INTO `atomicSkills` VALUES (62,'Планирование последовательности задач и шагов','',5);
INSERT INTO `atomicSkills` VALUES (63,'Синтез общих решений','',5);
INSERT INTO `atomicSkills` VALUES (64,'Анализ технических факторов','',5);
INSERT INTO `atomicSkills` VALUES (65,'Анализ бизнес-факторов','',5);
INSERT INTO `atomicSkills` VALUES (66,'Анализ затрат','',5);
INSERT INTO `atomicSkills` VALUES (67,'Анализ рисков','',5);
INSERT INTO `atomicSkills` VALUES (68,'Выявление сути задачи','',5);
INSERT INTO `atomicSkills` VALUES (69,'Работа с экспертами предметной области','',5);
INSERT INTO `atomicSkills` VALUES (70,'Предложение альтернативных вариантов','',5);
INSERT INTO `atomicSkills` VALUES (71,'Клиент-серверная архитектура','',6);
INSERT INTO `atomicSkills` VALUES (72,'Основные понятия веб','HTML, CSS, DOM, Ajax',6);
INSERT INTO `atomicSkills` VALUES (73,'Основы JavaScript','',6);
INSERT INTO `atomicSkills` VALUES (74,'Способы хранения и передачи состояния','Cookie, сессия',6);
INSERT INTO `atomicSkills` VALUES (75,'Основы HTML5','',6);
INSERT INTO `atomicSkills` VALUES (76,'Основы CSS3','',6);
INSERT INTO `atomicSkills` VALUES (77,'Основы SQL','',6);
INSERT INTO `atomicSkills` VALUES (78,'API браузера','Window, Document, LocalStorage, History и др.',6);
INSERT INTO `atomicSkills` VALUES (79,'Архитектурный стиль REST','',6);
INSERT INTO `atomicSkills` VALUES (80,'Протокол HTTP','',6);
INSERT INTO `atomicSkills` VALUES (81,'Протокол SOAP','',6);
INSERT INTO `atomicSkills` VALUES (82,'RESTful веб-службы','',6);
INSERT INTO `atomicSkills` VALUES (83,'Формат передачи данных JSON','',6);
INSERT INTO `atomicSkills` VALUES (84,'Формат передачи данных XML','',6);
INSERT INTO `atomicSkills` VALUES (85,'CRUD','',6);
INSERT INTO `atomicSkills` VALUES (86,'Принципы работы кэширования и сжатия','Gzip-сжатие, заголовки Last-Modified, Etag, Expires, Cache-control',6);
INSERT INTO `atomicSkills` VALUES (87,'Основные заголовки HTTP','Content-Encoding, Content-Type, Referer, User-Agent',6);
INSERT INTO `atomicSkills` VALUES (88,'CORS','',6);
INSERT INTO `atomicSkills` VALUES (89,'HTTP-статусы','200, 300, 400, 500',6);
INSERT INTO `atomicSkills` VALUES (90,'Работа с клиентами базы данных','',7);
INSERT INTO `atomicSkills` VALUES (91,'Базовые SQL-запросы (DML)','SELECT, INSERT, UPDATE, DELETE',7);
INSERT INTO `atomicSkills` VALUES (92,'Расширенные SQL-запросы (DML)','JOIN, ORDER BY, GROUP BY, HAVING, подзапросы',7);
INSERT INTO `atomicSkills` VALUES (93,'Запросы на изменение схемы (DDL)','',7);
INSERT INTO `atomicSkills` VALUES (94,'Использование функций SQL','',7);
INSERT INTO `atomicSkills` VALUES (95,'Аггрегатные функции SQL','MAX, MIN, SUM, AVG, GROUP_CONCAT',7);
INSERT INTO `atomicSkills` VALUES (96,'Виды','',7);
INSERT INTO `atomicSkills` VALUES (97,'Индексы','',7);
INSERT INTO `atomicSkills` VALUES (98,'Транзакции','',7);
INSERT INTO `atomicSkills` VALUES (99,'Атомарные операции','',7);
INSERT INTO `atomicSkills` VALUES (100,'Переменные SQL','',7);
INSERT INTO `atomicSkills` VALUES (101,'Хранимые процедуры SQL','',7);
INSERT INTO `atomicSkills` VALUES (102,'Разработка собственных функций SQL','',7);
INSERT INTO `atomicSkills` VALUES (103,'Курсор','',7);
INSERT INTO `atomicSkills` VALUES (104,'Триггер','',7);
INSERT INTO `atomicSkills` VALUES (105,'NoSQL','',7);
INSERT INTO `atomicSkills` VALUES (106,'Хранилища ключ-значение','MemcacheDB, Beanstalk, Redis',7);
INSERT INTO `atomicSkills` VALUES (107,'Нормальные формы','6 штук + доменно-ключевая + Бойса-Кодда',7);
INSERT INTO `atomicSkills` VALUES (108,'Целенаправленная денормализация','',7);
INSERT INTO `atomicSkills` VALUES (109,'ACID','',7);
INSERT INTO `atomicSkills` VALUES (110,'Теорема CAP','',7);
INSERT INTO `atomicSkills` VALUES (111,'Реализации SQL','MySQL, PostgreSQL, MSSQL, Oracle',7);
INSERT INTO `atomicSkills` VALUES (112,'Оптимизирование настроект серверов','',7);
INSERT INTO `atomicSkills` VALUES (113,'Кластеризация и репликация данных','',7);
INSERT INTO `atomicSkills` VALUES (114,'Колоночные базы данных','Hbase, Cassandra',7);
INSERT INTO `atomicSkills` VALUES (115,'Документ-ориентированные базы данных','CouchDB, MongoDB',7);
INSERT INTO `atomicSkills` VALUES (116,'Графовые базы данных','InfiniteGraph, FlockDB',7);
INSERT INTO `atomicSkills` VALUES (117,'Недостатки интуитивного подхода к анализу','',8);
INSERT INTO `atomicSkills` VALUES (118,'Консультации с коллегами','',8);
INSERT INTO `atomicSkills` VALUES (119,'Визуальный анализ','',8);
INSERT INTO `atomicSkills` VALUES (120,'A/B тестирование','',8);
INSERT INTO `atomicSkills` VALUES (121,'Техники многомерного анализа','Факторный анализ, кластерный анализ',8);
INSERT INTO `atomicSkills` VALUES (122,'Использование ПО для анализа данных','Microsoft Analysis Services, Pentaho Mondrian',8);
INSERT INTO `atomicSkills` VALUES (123,'MDX','',8);
INSERT INTO `atomicSkills` VALUES (124,'Data Warehouse','',8);
INSERT INTO `atomicSkills` VALUES (125,'Основы статистического анализа','Размер и принципы формирования выборки, дисперсия, среднее, медиана, доверительный интервал, значимость, дисперсия, p-значение, стандартное отклонение',8);
INSERT INTO `atomicSkills` VALUES (126,'Основные распределения','Нормальное, Стьюдента',8);
INSERT INTO `atomicSkills` VALUES (127,'Специализированное ПО для статистического анализа','Statistica, Matlab, R, SPSS',8);
INSERT INTO `atomicSkills` VALUES (128,'Математическое моделирование','',8);
INSERT INTO `atomicSkills` VALUES (129,'Подключение библиотек при помощи тэга script','',9);
INSERT INTO `atomicSkills` VALUES (130,'jQuery, jQuery-UI','',9);
INSERT INTO `atomicSkills` VALUES (131,'Backbone.js','',9);
INSERT INTO `atomicSkills` VALUES (132,'Underscore.js/Lodash','',9);
INSERT INTO `atomicSkills` VALUES (133,'Универсальные фреймворки для верстки','Bootstrap, Foundation, Skeleton и пр.',9);
INSERT INTO `atomicSkills` VALUES (134,'SPA-фреймворки','Angular.js, Vue.js, Ember.js, Meteor.js, React.js/Redux, i-bem.js',9);
INSERT INTO `atomicSkills` VALUES (135,'Модули JavaScript','AMD, CommonJS, ES6',9);
INSERT INTO `atomicSkills` VALUES (136,'Модульный CSS','',9);
INSERT INTO `atomicSkills` VALUES (137,'Системы сборки','Browserify, Webpack, Parcel',9);
INSERT INTO `atomicSkills` VALUES (138,'Менеджеры пакетов','bower, npm, yarn',9);
INSERT INTO `atomicSkills` VALUES (139,'Системы запуска задач','Gulp.js, Grunt',9);
INSERT INTO `atomicSkills` VALUES (140,'Препроцессоры CSS','SASS/SCSS, LESS, PostCSS',9);
INSERT INTO `atomicSkills` VALUES (141,'Препроцессоры JS','Babel',9);
INSERT INTO `atomicSkills` VALUES (142,'Линтеры','JSLint, JSHint, ESLint',9);
INSERT INTO `atomicSkills` VALUES (143,'Минификаторы/обфускаторы кода','Uglify.js, Google Closure Compiler, JSMin',9);
INSERT INTO `atomicSkills` VALUES (144,'Оптимизаторы кода','Prepack',9);
INSERT INTO `atomicSkills` VALUES (145,'Архитектуры SPA','',9);
INSERT INTO `atomicSkills` VALUES (146,'Отладка JavaScipt кода','',9);
INSERT INTO `atomicSkills` VALUES (147,'TypeScript','',9);
INSERT INTO `atomicSkills` VALUES (148,'CoffeeScript','',9);
INSERT INTO `atomicSkills` VALUES (149,'Базовый синтаксис языка','Переменные, циклы, условия, функции, классы',10);
INSERT INTO `atomicSkills` VALUES (150,'Способы организации наследования','Модель конструктора, функциональная, прототипная, OLOO, ES6',10);
INSERT INTO `atomicSkills` VALUES (151,'Области видимости','Динамические, лексические',10);
INSERT INTO `atomicSkills` VALUES (152,'Контекст this','',10);
INSERT INTO `atomicSkills` VALUES (153,'Типизация в JavaScript','',10);
INSERT INTO `atomicSkills` VALUES (154,'Приведение к общему типу (coercion)','',10);
INSERT INTO `atomicSkills` VALUES (155,'Реализация асинхронности в JavaScript','',10);
INSERT INTO `atomicSkills` VALUES (156,'Promise','',10);
INSERT INTO `atomicSkills` VALUES (157,'Разработка на ванильном JS','',10);
INSERT INTO `atomicSkills` VALUES (158,'Оптимизация производительности','',10);
INSERT INTO `atomicSkills` VALUES (159,'Стандарт ES2015/ES6','',10);
INSERT INTO `atomicSkills` VALUES (160,'Стандарты ES6+','',10);
INSERT INTO `atomicSkills` VALUES (161,'Async/await','',10);
INSERT INTO `atomicSkills` VALUES (162,'Генераторы','',10);
INSERT INTO `atomicSkills` VALUES (163,'Реактивное программирование','rx, bacon, kefir',10);
INSERT INTO `atomicSkills` VALUES (164,'Перекрытие (shadowing) переменных','',10);
INSERT INTO `atomicSkills` VALUES (165,'Поднятие (hoisting) переменных','',10);
INSERT INTO `atomicSkills` VALUES (166,'Немедленно вызываемые функции (IIFE)','',10);
INSERT INTO `atomicSkills` VALUES (167,'Паттерны оптимизации','',10);
INSERT INTO `atomicSkills` VALUES (168,'Режим полного соответствия стандарту','',10);
INSERT INTO `atomicSkills` VALUES (169,'Глобальный объект','',10);
INSERT INTO `atomicSkills` VALUES (170,'Цепь областей видимости','',10);
INSERT INTO `atomicSkills` VALUES (171,'Цепь прототипов','',10);
INSERT INTO `atomicSkills` VALUES (172,'Стандартная библиотека (SPL)','',11);
INSERT INTO `atomicSkills` VALUES (173,'Основные расширения','mcrypt, xml, mbstring, gd, imagick, mysqli и пр.',11);
INSERT INTO `atomicSkills` VALUES (174,'Автозагрузка','',11);
INSERT INTO `atomicSkills` VALUES (175,'Composer','',11);
INSERT INTO `atomicSkills` VALUES (176,'Pear','',11);
INSERT INTO `atomicSkills` VALUES (177,'PSR-0','',11);
INSERT INTO `atomicSkills` VALUES (178,'PSR-4','',11);
INSERT INTO `atomicSkills` VALUES (179,'Разработка на фреймворках','Symfony 2/3, Laravel 4/5, Yii 1/2, Zend Framework 1/2 и пр.',11);
INSERT INTO `atomicSkills` VALUES (180,'Использование PDO','',11);
INSERT INTO `atomicSkills` VALUES (181,'Использование ORM','Propel, Eloquent, Doctrine',11);
INSERT INTO `atomicSkills` VALUES (182,'Работа с популярными библиотеками','Carbon, ImageWorkshop, Twig, Guzzle, Goutte, SwiftMailer, Mockery, библиотеки The PHP League',11);
INSERT INTO `atomicSkills` VALUES (183,'Отладка кода','IDE, Xdebug',11);
INSERT INTO `atomicSkills` VALUES (184,'Системы очередей','ZMQ, RabbitMQ, ActiveMQ, Amazon SQS',11);
INSERT INTO `atomicSkills` VALUES (185,'Поисковые системы','Apache Lucene, Apache Solr, Elasticsearch, Sphinx',11);
INSERT INTO `atomicSkills` VALUES (186,'Разработка монолитных приложений','',11);
INSERT INTO `atomicSkills` VALUES (187,'Разработка микросервисных приложений','',11);
INSERT INTO `atomicSkills` VALUES (188,'Авторизация и аутентификация','Протоколы OAuth 1/2, OpenID, JWT. Системы с ACL',11);
INSERT INTO `atomicSkills` VALUES (189,'Бэкенд разработка на других языках','JavaScript/NodeJS, Ruby',11);
INSERT INTO `atomicSkills` VALUES (190,'Фреймворки прочих языков','Express, Koa, Rails',11);
INSERT INTO `atomicSkills` VALUES (191,'Работа с высоконагруженными системами','',11);
INSERT INTO `atomicSkills` VALUES (192,'Работа с большими объемами данных','',11);
INSERT INTO `atomicSkills` VALUES (193,'Исправление багов в библиотеках, платформах','',11);
INSERT INTO `atomicSkills` VALUES (194,'Резервное копирование кода','',12);
INSERT INTO `atomicSkills` VALUES (195,'Основы систем контроля версий','Фиксация изменений, ветвления, отправка и получение данных',12);
INSERT INTO `atomicSkills` VALUES (196,'Прочие операции','Перемещение и слияние кода, изменение и удаление коммитов, работа с несколькими репозиториями',12);
INSERT INTO `atomicSkills` VALUES (197,'Способы совместной работы','Централизованная работа, feature branch, gitflow, forking workflow',12);
INSERT INTO `atomicSkills` VALUES (199,'Хуки','',12);
INSERT INTO `atomicSkills` VALUES (200,'Интеграция с внешними скриптами','',12);
INSERT INTO `atomicSkills` VALUES (201,'Ручная минификация и оптимизация файлов','',13);
INSERT INTO `atomicSkills` VALUES (202,'Конфигурирование системам сборки','Gulp, Grunt, Webpack',13);
INSERT INTO `atomicSkills` VALUES (203,'Многовходовая сборка','',13);
INSERT INTO `atomicSkills` VALUES (204,'Нестандартные кофигурации','',13);
INSERT INTO `atomicSkills` VALUES (205,'Сборка legacy-кода','',13);
INSERT INTO `atomicSkills` VALUES (206,'Объединение систем на нескольких фреймворках','',13);
INSERT INTO `atomicSkills` VALUES (207,'Работа с ОС на уровне пользователя','',14);
INSERT INTO `atomicSkills` VALUES (208,'Установка и удаление программ','',14);
INSERT INTO `atomicSkills` VALUES (209,'Подключение к сетям','',14);
INSERT INTO `atomicSkills` VALUES (210,'Консоль','',14);
INSERT INTO `atomicSkills` VALUES (211,'Консольные команды','',14);
INSERT INTO `atomicSkills` VALUES (212,'Скрипты','',14);
INSERT INTO `atomicSkills` VALUES (213,'Конфигурационные файлы/реестр','',14);
INSERT INTO `atomicSkills` VALUES (214,'Работа с драйверами и оборудованием','',14);
INSERT INTO `atomicSkills` VALUES (215,'Виртуализация','',14);
INSERT INTO `atomicSkills` VALUES (216,'Установка ОС','',14);
INSERT INTO `atomicSkills` VALUES (217,'Работа с ОС на уровне системного администрирования','',14);
INSERT INTO `atomicSkills` VALUES (218,'Установка и настройка серверных программ','',14);
INSERT INTO `atomicSkills` VALUES (219,'Организация сетевого взаимодействия','',14);
INSERT INTO `atomicSkills` VALUES (220,'Архитектура компьютера','',14);
INSERT INTO `atomicSkills` VALUES (221,'Сетевые коммуникационные протоколы','IPv4, IPv6, TCP, UDP, POP, IMAP, SMTP, HTTP, SMB',14);
INSERT INTO `atomicSkills` VALUES (222,'Веб-сервер','Apache, Nginx, lighthttpd',14);
INSERT INTO `atomicSkills` VALUES (223,'СУБД','MySQL, PostgreSQL',14);
INSERT INTO `atomicSkills` VALUES (224,'Системы управления конфигурациями','Puppet, Chef, Ansible, Salt',14);
INSERT INTO `atomicSkills` VALUES (225,'Контейнеризация','Vagrant, docker, docker-compose, kubernetes',14);
INSERT INTO `atomicSkills` VALUES (226,'SSH','',14);
INSERT INTO `atomicSkills` VALUES (227,'VPN','OpenVPN, pptpd',14);
INSERT INTO `atomicSkills` VALUES (228,'SSL','OpenSSL, Let“s Encrypt',14);
INSERT INTO `atomicSkills` VALUES (229,'Хостинг','',15);
INSERT INTO `atomicSkills` VALUES (230,'Amazon','',15);
INSERT INTO `atomicSkills` VALUES (231,'Digital Ocean','',15);
INSERT INTO `atomicSkills` VALUES (232,'Выгрузка при помощи FTP/SFTP','',15);
INSERT INTO `atomicSkills` VALUES (233,'Git','',15);
INSERT INTO `atomicSkills` VALUES (234,'Миграции БД','',15);
INSERT INTO `atomicSkills` VALUES (235,'Системы CI','Jenkins, TeamCity, Travis-CI, GitlabCI',15);
INSERT INTO `atomicSkills` VALUES (236,'Практики DevOps','ChatOps, IaS, Docker, пайплайны',15);
INSERT INTO `atomicSkills` VALUES (237,'Системы мониторинга','Prometheus, Zabbix',15);
INSERT INTO `atomicSkills` VALUES (238,'Kubernetes','',15);
INSERT INTO `atomicSkills` VALUES (239,'Инфраструктурная организация рефакторинга БД','',15);
INSERT INTO `atomicSkills` VALUES (240,'Использование для написания кода','',16);
INSERT INTO `atomicSkills` VALUES (241,'Установка и настройка расширений','',16);
INSERT INTO `atomicSkills` VALUES (242,'Настройка автокоррекции синтаксиса','',16);
INSERT INTO `atomicSkills` VALUES (243,'Функции рефакторинга кода','Переименование переменных, функций, классов',16);
INSERT INTO `atomicSkills` VALUES (244,'Работа с системой контроля версий','',16);
INSERT INTO `atomicSkills` VALUES (245,'Работа с базой данных','',16);
INSERT INTO `atomicSkills` VALUES (246,'Использование профилировщика','',16);
INSERT INTO `atomicSkills` VALUES (247,'Управляющие комбинации клавиш','',16);
INSERT INTO `atomicSkills` VALUES (248,'Разные IDE','IntelliJ IDEA, VS Code, Eclipse',16);
INSERT INTO `atomicSkills` VALUES (249,'Работа в одиночку','',17);
INSERT INTO `atomicSkills` VALUES (250,'Работа в кроссфункциональной команде','',17);
INSERT INTO `atomicSkills` VALUES (251,'Устранение конфликтов в коде при помощи VCS','',17);
INSERT INTO `atomicSkills` VALUES (252,'Поддержание общего домена знаний','Документирование, рассказ о наработках, ответы на вопросы',17);
INSERT INTO `atomicSkills` VALUES (253,'Парное программирование','',17);
INSERT INTO `atomicSkills` VALUES (254,'Разработка по каскадной методологии','',17);
INSERT INTO `atomicSkills` VALUES (255,'Гибкие методологии разработки','Scrum, kanban',17);
INSERT INTO `atomicSkills` VALUES (256,'Организация процесса разработки','',17);
INSERT INTO `atomicSkills` VALUES (257,'Работа без менеджеров','',17);
INSERT INTO `atomicSkills` VALUES (258,'Принятие решений по собственным ощущениям','',18);
INSERT INTO `atomicSkills` VALUES (259,'Использование данных и фактов для формирования решения','',18);
INSERT INTO `atomicSkills` VALUES (260,'Консультации с коллегами для принятия решения','',18);
INSERT INTO `atomicSkills` VALUES (261,'Навыки безопасной коммуникации','',18);
INSERT INTO `atomicSkills` VALUES (262,'Навыки активного слушания','',18);
INSERT INTO `atomicSkills` VALUES (263,'Использование поисковой системы для поиска решений','',19);
INSERT INTO `atomicSkills` VALUES (264,'Чтение технической литературы','',19);
INSERT INTO `atomicSkills` VALUES (265,'Понимание своих сильных и слабых сторон','',19);
INSERT INTO `atomicSkills` VALUES (266,'Обучение коллег','',19);
INSERT INTO `atomicSkills` VALUES (267,'Подготовка образовательных материалов','',19);
INSERT INTO `atomicSkills` VALUES (268,'Регулярное дистанционное обучение','',19);
INSERT INTO `atomicSkills` VALUES (269,'Регулярное очное обучение','',19);
INSERT INTO `atomicSkills` VALUES (270,'Написание технических статей или записей в блоге','',19);
INSERT INTO `atomicSkills` VALUES (271,'Участие в конференциях в качестве слушателя','',19);
INSERT INTO `atomicSkills` VALUES (272,'Участие в конференциях в качестве докладчика','',19);
INSERT INTO `atomicSkills` VALUES (273,'Поверхностная ревизия','По формальным критериям вроде именования, стилистики, местоположения файлов',20);
INSERT INTO `atomicSkills` VALUES (274,'Глубокая ревизия кода','По всем критериям, включая смысл кода, используемые алгоритмы, соответствие задаче, оптимальность алгоритма и архитектурную корректность',20);
INSERT INTO `atomicSkills` VALUES (275,'Позитивная обратная связь по коду','',20);
INSERT INTO `atomicSkills` VALUES (276,'Формирование предложений и идей','Чем больше идей, тем лучше',20);
INSERT INTO `atomicSkills` VALUES (277,'Ревизия кода в больших задачах','Когда кода много',20);
INSERT INTO `atomicSkills` VALUES (278,'Использование автоматизированных средств для ревизии','',20);
INSERT INTO `atomicSkills` VALUES (279,'Оценка по собственным ощущениям','',21);
INSERT INTO `atomicSkills` VALUES (280,'Оценка с поправочным коэффициентом','',21);
INSERT INTO `atomicSkills` VALUES (281,'Оценка сроков через сложность задачи','',21);
INSERT INTO `atomicSkills` VALUES (282,'Круговая/коллективная оценка','Покер планирования',21);
INSERT INTO `atomicSkills` VALUES (283,'Оценка вилкой по двум точкам','Минимум, максимум',21);
INSERT INTO `atomicSkills` VALUES (284,'Оценка вилкой с тремя точками','Минимум, максимум, наиболее вероятный срок',21);
INSERT INTO `atomicSkills` VALUES (285,'Скорость команды и диаграмма сгорания','',21);
INSERT INTO `atomicSkills` VALUES (286,'Работа с проектами с небольшим сроком жизни','',22);
INSERT INTO `atomicSkills` VALUES (287,'Переписывание проектов «с нуля»','',22);
INSERT INTO `atomicSkills` VALUES (288,'Предел технической сложности проекта','',22);
INSERT INTO `atomicSkills` VALUES (289,'Работа с техническим долгом','',22);
INSERT INTO `atomicSkills` VALUES (290,'Рефакторинг','',22);
INSERT INTO `atomicSkills` VALUES (291,'Работа с «хрупкими комками грязи»','Сложными проектами с хрупким кодом и большим legacy',22);
INSERT INTO `atomicSkills` VALUES (292,'Стабилизация скорости разработки проектов','',22);
INSERT INTO `atomicSkills` VALUES (293,'Изучение исходных текстов продуктов','',23);
INSERT INTO `atomicSkills` VALUES (294,'Изучение багтреккеров продуктов','',23);
INSERT INTO `atomicSkills` VALUES (295,'Оформление PRов к продуктам с открытым кодом','',23);
INSERT INTO `atomicSkills` VALUES (296,'Решение PRов, подготовка пулл-запросов','',23);
INSERT INTO `atomicSkills` VALUES (297,'Постоянная поддержка проекта с открытым кодом','',23);
INSERT INTO `atomicSkills` VALUES (298,'Участие в Open Source сообществах','',23);
INSERT INTO `atomicSkills` VALUES (299,'Знание иностранного языка на уровне чтения документации','Beginner, Elementary, Pre-Intermediate',24);
INSERT INTO `atomicSkills` VALUES (300,'Знание на уровне полноценного письменного общения','Intermediate, Upper-Intermediate',24);
INSERT INTO `atomicSkills` VALUES (301,'Понимание устной речи','',24);
INSERT INTO `atomicSkills` VALUES (302,'Поддержка разговоров на технические темы','',24);
INSERT INTO `atomicSkills` VALUES (303,'Поддержка разговоров на бытовые темы','',24);
INSERT INTO `atomicSkills` VALUES (304,'Деловая и техническая переписка','',24);
INSERT INTO `atomicSkills` VALUES (305,'Знание на уровне свободного владения языка','Advanced, Proficiency',24);
INSERT INTO `atomicSkills` VALUES (306,'Сертификация знаний иностранного языка','TOEFL, IELTS',24);
INSERT INTO `atomicSkills` VALUES (307,'Размещения, перестановки, сочетания','',27);
INSERT INTO `atomicSkills` VALUES (308,'Биномиальные коэффициенты','',27);
INSERT INTO `atomicSkills` VALUES (309,'Математическое ожидание','',27);
INSERT INTO `atomicSkills` VALUES (310,'Дисперсия','',27);
INSERT INTO `atomicSkills` VALUES (311,'Условная вероятность','',27);
INSERT INTO `atomicSkills` VALUES (312,'Основные распределения','Нормальное, биномиальное, Стьюдента, Пуассона, Трейси-Видома',27);
INSERT INTO `atomicSkills` VALUES (313,'Основные понятия','Тест-план, Тест-кейс, баг',28);
INSERT INTO `atomicSkills` VALUES (314,'Эффект пестицида','',28);
INSERT INTO `atomicSkills` VALUES (315,'Работа с багтреккером','',28);
INSERT INTO `atomicSkills` VALUES (316,'Работа с функциональными требованиями','',28);
INSERT INTO `atomicSkills` VALUES (317,'Классы эквивалентности','',28);
INSERT INTO `atomicSkills` VALUES (318,'Формирование разбиения области тестирования','',28);
INSERT INTO `atomicSkills` VALUES (319,'Анализ границ области тестирования','',28);
INSERT INTO `atomicSkills` VALUES (320,'Методики тестирования','Черный, белый и серый ящики',28);
INSERT INTO `atomicSkills` VALUES (321,'Виды тестирования','Компонентное, системное, интеграционное. Регрессионное, стресс, приёмочное',28);
INSERT INTO `atomicSkills` VALUES (322,'Построение тест-плана','',28);
INSERT INTO `atomicSkills` VALUES (323,'Построение тест-кейсов','',28);
INSERT INTO `atomicSkills` VALUES (324,'Причинно-следственные диаграммы','',28);
INSERT INTO `atomicSkills` VALUES (325,'Анализ модели состояния','',28);
INSERT INTO `atomicSkills` VALUES (326,'Оценка покрытия кода и требований тестами','Покрытие функций, условий, решений',28);
INSERT INTO `atomicSkills` VALUES (327,'Основные понятия веб-разработки','Веб-сервер, веб-клиент, POST-запросы, GET-запросы',28);
INSERT INTO `atomicSkills` VALUES (328,'Использование средств перехвата запросов','Fiddler',28);
INSERT INTO `atomicSkills` VALUES (329,'Протоколы веб','HTTP, JSON, FTP, telnet, SMTP, POP',28);
INSERT INTO `atomicSkills` VALUES (330,'Тестирование защищенности веб-приложений','',28);
INSERT INTO `atomicSkills` VALUES (331,'SQL-инъекции','',28);
INSERT INTO `atomicSkills` VALUES (332,'XSS','',28);
INSERT INTO `atomicSkills` VALUES (333,'Нагрузочное тестирование','JMeter, HP Load Runner, ab, siege',28);
INSERT INTO `atomicSkills` VALUES (334,'Сборка динамического покрытия кода тестами','',28);
INSERT INTO `atomicSkills` VALUES (335,'Знание языка программирования','Python, java, javascript, C#',29);
INSERT INTO `atomicSkills` VALUES (336,'Использование IDE','',29);
INSERT INTO `atomicSkills` VALUES (337,'Инструменты записи сценариев','',29);
INSERT INTO `atomicSkills` VALUES (338,'Инспекция кода','',29);
INSERT INTO `atomicSkills` VALUES (339,'Тест-дизайн','',29);
INSERT INTO `atomicSkills` VALUES (340,'Средства отладки в CLI и IDE','',29);
INSERT INTO `atomicSkills` VALUES (341,'Использование Selenium','или надстроек Appium, Winium, Windows Application Driver',29);
INSERT INTO `atomicSkills` VALUES (342,'Data Driven Testing','',29);
INSERT INTO `atomicSkills` VALUES (343,'Behaviour Driven Testing','',29);
INSERT INTO `atomicSkills` VALUES (344,'Model Driven Testing','',29);
INSERT INTO `atomicSkills` VALUES (345,'Keyword Driven Testing','',29);
INSERT INTO `atomicSkills` VALUES (346,'Шаблоны проектирования тестов','Functional, PageObjects',29);
INSERT INTO `atomicSkills` VALUES (347,'Распределенное тестирование','',29);
INSERT INTO `atomicSkills` VALUES (348,'Selenium Server','',29);
INSERT INTO `atomicSkills` VALUES (349,'Selenium Grid','',29);
INSERT INTO `atomicSkills` VALUES (350,'Облачные сервисы тестирования','',29);
INSERT INTO `atomicSkills` VALUES (351,'Встроенные типы переменных','',26);
INSERT INTO `atomicSkills` VALUES (352,'Mutable/immutable типы','',26);
INSERT INTO `atomicSkills` VALUES (353,'Динамическая типизация','',26);
INSERT INTO `atomicSkills` VALUES (354,'Базовый синтаксис языка','И инструкции управления потоком выполнения',26);
INSERT INTO `atomicSkills` VALUES (355,'Синтаксис функций','',26);
INSERT INTO `atomicSkills` VALUES (356,'Области видимости переменных','Правило LEGB',26);
INSERT INTO `atomicSkills` VALUES (357,'Итераторы','',26);
INSERT INTO `atomicSkills` VALUES (358,'Генераторы','',26);
INSERT INTO `atomicSkills` VALUES (359,'Документирование кода','В соответствии с PEP8',26);
INSERT INTO `atomicSkills` VALUES (360,'Средства функционального программирования','map, filter, reduce',26);
INSERT INTO `atomicSkills` VALUES (361,'Анонимные функции (lambda)','',26);
INSERT INTO `atomicSkills` VALUES (362,'Использование инструкции yield','',26);
INSERT INTO `atomicSkills` VALUES (363,'Проектирование модулей','',26);
INSERT INTO `atomicSkills` VALUES (364,'Работа с модулями','Повторная загрузка, относительный импорт, сокрытие данных',26);
INSERT INTO `atomicSkills` VALUES (365,'Классы, создание и использование','',26);
INSERT INTO `atomicSkills` VALUES (366,'Наследование и переопределение методов','',26);
INSERT INTO `atomicSkills` VALUES (367,'Композиция и делегирование для классов','',26);
INSERT INTO `atomicSkills` VALUES (368,'Перегрузка операторов','',26);
INSERT INTO `atomicSkills` VALUES (369,'Фабрики объектов','',26);
INSERT INTO `atomicSkills` VALUES (370,'Классы \"старого\" и \"нового\" стилей','',26);
INSERT INTO `atomicSkills` VALUES (371,'Создание и использование исключений','',26);
INSERT INTO `atomicSkills` VALUES (372,'Создание и использование контекстных менеджеров','',26);
INSERT INTO `atomicSkills` VALUES (373,'Объекты unicode, bytes, bytearray','',26);
INSERT INTO `atomicSkills` VALUES (374,'Env-сборки','При помощи утилиты pip',26);
INSERT INTO `atomicSkills` VALUES (375,'Консольный отладчик python','',26);
INSERT INTO `atomicSkills` VALUES (376,'Декораторы функций','',26);
INSERT INTO `atomicSkills` VALUES (377,'Декораторы классов','',26);
INSERT INTO `atomicSkills` VALUES (378,'Дескрипторы','',26);
INSERT INTO `atomicSkills` VALUES (379,'Множественное наследование','',26);
INSERT INTO `atomicSkills` VALUES (380,'Различные варианты python','cpython, ironpython, jpython, Stackless Python',26);
INSERT INTO `atomicSkills` VALUES (381,'Разработка с веб-фреймворками','Django, Flask, Pyramid',26);
INSERT INTO `atomicSkills` VALUES (382,'Разработка с GUI-фреймворками','PyQt, Tkinter, WxPython',26);
INSERT INTO `atomicSkills` VALUES (383,'Метапрограммирование','',26);
INSERT INTO `atomicSkills` VALUES (384,'Сетевое программирование','',26);
INSERT INTO `atomicSkills` VALUES (385,'Асинхронное программирование','',26);
INSERT INTO `atomicSkills` VALUES (386,'Мультипроцессное программирование','',26);
INSERT INTO `atomicSkills` VALUES (387,'Мультипоточное программирование','',26);
INSERT INTO `atomicSkills` VALUES (388,'Специализированные библиотеки','NumPy, SciPy, SQLAlchemy',26);
INSERT INTO `atomicSkills` VALUES (389,'«Великодушный пожизненный диктатор»','',26);
INSERT INTO `atomicSkills` VALUES (390, 'CVS', null, 12);
INSERT INTO `atomicSkills` VALUES (391, 'SVN', null, 12);
INSERT INTO `atomicSkills` VALUES (392, 'Git', null, 12);
INSERT INTO `atomicSkills` VALUES (393, 'Mercurial', null, 12);
INSERT INTO `atomicSkills` VALUES (394, 'Fossil', null, 12);