UPDATE `competencies` SET `code`='pmSelfDiscipline', `name`='Личная дисциплина' WHERE `id`='35';
UPDATE `competencies` SET `name`='Управление рисками' WHERE `id`='46';
UPDATE `competencies` SET `name`='Ведение встреч' WHERE `id`='39';
UPDATE `competencies` SET `name`='Планирование и управление' WHERE `id`='43';
UPDATE `competencies` SET `code`='pmTeamWork', `name`='Работа с командой' WHERE `id`='44';
UPDATE `competencies` SET `name`='Работа с продуктом' WHERE `id`='45';
UPDATE `competencies` SET `name`='Итерации и ритуалы гибких методологий' WHERE `id`='51';
INSERT INTO `competencies` (`id`, `code`, `name`, `competencyGroupId`) VALUES ('53', 'pmQuality', 'Управление качеством', '13');
INSERT INTO `competencies` (`id`, `code`, `name`, `competencyGroupId`) VALUES ('54', 'pmOrgManagement', 'Управление организацией', '13');
INSERT INTO `competencies` (`id`, `code`, `name`, `competencyGroupId`) VALUES ('55', 'pmProjectMethods', 'Методологии ведения проектов', '13');


CREATE TABLE `atomicSkills` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `text` text DEFAULT NULL,
  `additionalDescription` text DEFAULT NULL,
  `competencyId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=390 DEFAULT CHARSET=utf8;


INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Базовые алгоритмы', 'Линейный поиск, сортировка и бинарный поиск, обход многомерного массива', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Векторные и матричные операции', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Сложные типы данных', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Рекурсия', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Лямбда функции', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Карринг', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Функции высшего порядка', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Чистота функций', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Побочные эффекты функций', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Замыкания', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Понятие вычислимости', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Машина Тьюринга', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Конечные автоматы', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Классы вычислительной сложности', 'O(N), O(N*log(N)), O(N!), ..., P, FP, NP', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('NP-полнота', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Алгоритм NP-перебора', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Параллельные алгоритмы', 'Очередь, конвейер', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Транзакции', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Мертвая блокировка', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Состояние гонки', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Семафоры', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Мьютексы', '', '1');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Базовые понятия ООП', 'Абстракция, инкапсуляция, наследование, полиморфизм', '2');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Инкапсуляция данных', 'Приватные методы', '2');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Интерфейс', '', '2');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Абстрактный класс', '', '2');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Простые шаблоны проектирования', 'Одиночка (singleton), фабрика (factory), фасад (fascade), адаптер (adapter)', '2');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Расширение без наследования', 'Композиция, полиморфные классы, шаблонные методы', '2');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Сериализация объектов', 'И десериализация', '2');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Дополнительные шаблоны проектирования', 'Наблюдатель (observer), посетитель (visitor), стратегия (strategy), реестр (registry)', '2');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('DI-фрейморки', '', '2');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Архитектурные принципы ООП', 'SRP, OCP, LSP, ISP, DIP (SOLID), DRY, KISS, YAGNI', '2');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Архитектурные шаблоны', 'MVC, MVP, MVVM, DDD', '2');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Организация и оформление кода', 'По файлам, папкам, PSR-0, PSR-1, PSR-2, PSR-4', '2');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Понятное именование', 'Переменных, объектов, классов, функций, таблиц', '3');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основные запахи кода', 'Дублирование кода, мертвый код, операторы switch, стрельба дробью, завистливые функции и пр.', '3');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Базовые техники рефакторинга', 'Извлечение/перемещение метода, класса, удаление посредника, инкапсуляция поля, замена параметров объектом, свертывание иерархии и пр.', '3');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Правило бойскаута', 'Оставь поляну лучше, чем она была до тебя', '3');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Переиспользуемый код', '', '3');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Практики экстремального программирования', 'Парное программирование, заказчик всегда рядом, непрерывная интеграция, частые релизы и пр.', '3');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Комментирование и документирование', '', '3');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Модульные тесты', '', '3');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('TDD/BDD', '', '3');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Скорость через улучшение качества', '', '3');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Ревизия кода', '', '3');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Гибкость кода', '', '3');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Частые запуски автотестов', '', '4');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Разработка модульных тестов', '', '4');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Cредства и фреймоврки тестирования PHP', 'PHPUnit, Atoum, Simpletest, Behat, Mink, Codeception, Mockery', '4');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Средства и фреймворки тестирования JavaScript', 'Jasmine, qunit, nightwatch, jest, chai, mocha, assert', '4');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основные понятия тестирования', 'Тест-план, тест-дизайн, тест-анализ. Методы чёрного ящика, белого и серого ящика', '4');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Написание баг-репортов', '', '4');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Классы эквивалентности', '', '4');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Прочие виды тестирования', 'Интеграционное, системное, функциональное, регрессионное, приемочное и пр.', '4');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Средства автоматизации тестирования UI', 'Selenium, appium', '4');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Data-driven тестирование', '', '4');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Методики автоматизированного тестирования', 'Keyword-driven, Behavior-driven, Model-based', '4');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с менеджментом', '', '5');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Инициативность в получении информации', '', '5');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Анализ возможных вариантов решения', '', '5');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Декомпозиция сложных задач', '', '5');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Планирование последовательности задач и шагов', '', '5');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Синтез общих решений', '', '5');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Анализ технических факторов', '', '5');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Анализ бизнес-факторов', '', '5');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Анализ затрат', '', '5');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Анализ рисков', '', '5');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Выявление сути задачи', '', '5');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с экспертами предметной области', '', '5');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Предложение альтернативных вариантов', '', '5');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Клиент-серверная архитектура', '', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основные понятия веб', 'HTML, CSS, DOM, Ajax', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основы JavaScript', '', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Способы хранения и передачи состояния', 'Cookie, сессия', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основы HTML5', '', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основы CSS3', '', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основы SQL', '', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('API браузера', 'Window, Document, LocalStorage, History и др.', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Архитектурный стиль REST', '', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Протокол HTTP', '', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Протокол SOAP', '', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('RESTful веб-службы', '', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Формат передачи данных JSON', '', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Формат передачи данных XML', '', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('CRUD', '', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Принципы работы кэширования и сжатия', 'Gzip-сжатие, заголовки Last-Modified, Etag, Expires, Cache-control', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основные заголовки HTTP', 'Content-Encoding, Content-Type, Referer, User-Agent', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('CORS', '', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('HTTP-статусы', '200, 300, 400, 500', '6');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с клиентами базы данных', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Базовые SQL-запросы (DML)', 'SELECT, INSERT, UPDATE, DELETE', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Расширенные SQL-запросы (DML)', 'JOIN, ORDER BY, GROUP BY, HAVING, подзапросы', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Запросы на изменение схемы (DDL)', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Использование функций SQL', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Аггрегатные функции SQL', 'MAX, MIN, SUM, AVG, GROUP_CONCAT', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Виды', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Индексы', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Транзакции', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Атомарные операции', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Переменные SQL', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Хранимые процедуры SQL', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Разработка собственных функций SQL', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Курсор', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Триггер', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('NoSQL', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Хранилища ключ-значение', 'MemcacheDB, Beanstalk, Redis', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Нормальные формы', '6 штук + доменно-ключевая + Бойса-Кодда', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Целенаправленная денормализация', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('ACID', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Теорема CAP', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Реализации SQL', 'MySQL, PostgreSQL, MSSQL, Oracle', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Оптимизирование настроект серверов', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Кластеризация и репликация данных', '', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Колоночные базы данных', 'Hbase, Cassandra', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Документ-ориентированные базы данных', 'CouchDB, MongoDB', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Графовые базы данных', 'InfiniteGraph, FlockDB', '7');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Недостатки интуитивного подхода к анализу', '', '8');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Консультации с коллегами', '', '8');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Визуальный анализ', '', '8');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('A/B тестирование', '', '8');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Техники многомерного анализа', 'Факторный анализ, кластерный анализ', '8');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Использование ПО для анализа данных', 'Microsoft Analysis Services, Pentaho Mondrian', '8');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('MDX', '', '8');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Data Warehouse', '', '8');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основы статистического анализа', 'Размер и принципы формирования выборки, дисперсия, среднее, медиана, доверительный интервал, значимость, дисперсия, p-значение, стандартное отклонение', '8');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основные распределения', 'Нормальное, Стьюдента', '8');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Специализированное ПО для статистического анализа', 'Statistica, Matlab, R, SPSS', '8');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Математическое моделирование', '', '8');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Подключение библиотек при помощи тэга script', '', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('jQuery, jQuery-UI', '', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Backbone.js', '', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Underscore.js/Lodash', '', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Универсальные фреймворки для верстки', 'Bootstrap, Foundation, Skeleton и пр.', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('SPA-фреймворки', 'Angular.js, Vue.js, Ember.js, Meteor.js, React.js/Redux, i-bem.js', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Модули JavaScript', 'AMD, CommonJS, ES6', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Модульный CSS', '', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Системы сборки', 'Browserify, Webpack, Parcel', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Менеджеры пакетов', 'bower, npm, yarn', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Системы запуска задач', 'Gulp.js, Grunt', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Препроцессоры CSS', 'SASS/SCSS, LESS, PostCSS', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Препроцессоры JS', 'Babel', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Линтеры', 'JSLint, JSHint, ESLint', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Минификаторы/обфускаторы кода', 'Uglify.js, Google Closure Compiler, JSMin', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Оптимизаторы кода', 'Prepack', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Архитектуры SPA', '', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Отладка JavaScipt кода', '', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('TypeScript', '', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('CoffeeScript', '', '9');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Базовый синтаксис языка', 'Переменные, циклы, условия, функции, классы', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Способы организации наследования', 'Модель конструктора, функциональная, прототипная, OLOO, ES6', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Области видимости', 'Динамические, лексические', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Контекст this', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Типизация в JavaScript', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Приведение к общему типу (coercion)', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Реализация асинхронности в JavaScript', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Promise', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Разработка на ванильном JS', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Оптимизация производительности', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Стандарт ES2015/ES6', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Стандарты ES6+', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Async/await', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Генераторы', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Реактивное программирование', 'rx, bacon, kefir', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Перекрытие (shadowing) переменных', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Поднятие (hoisting) переменных', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Немедленно вызываемые функции (IIFE)', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Паттерны оптимизации', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Режим полного соответствия стандарту', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Глобальный объект', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Цепь областей видимости', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Цепь прототипов', '', '10');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Стандартная библиотека (SPL)', '', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основные расширения', 'mcrypt, xml, mbstring, gd, imagick, mysqli и пр.', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Автозагрузка', '', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Composer', '', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Pear', '', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('PSR-0', '', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('PSR-4', '', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Разработка на фреймворках', 'Symfony 2/3, Laravel 4/5, Yii 1/2, Zend Framework 1/2 и пр.', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Использование PDO', '', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Использование ORM', 'Propel, Eloquent, Doctrine', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с популярными библиотеками', 'Carbon, ImageWorkshop, Twig, Guzzle, Goutte, SwiftMailer, Mockery, библиотеки The PHP League', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Отладка кода', 'IDE, Xdebug', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Системы очередей', 'ZMQ, RabbitMQ, ActiveMQ, Amazon SQS', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Поисковые системы', 'Apache Lucene, Apache Solr, Elasticsearch, Sphinx', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Разработка монолитных приложений', '', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Разработка микросервисных приложений', '', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Авторизация и аутентификация', 'Протоколы OAuth 1/2, OpenID, JWT. Системы с ACL', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Бэкенд разработка на других языках', 'JavaScript/NodeJS, Ruby', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Фреймворки прочих языков', 'Express, Koa, Rails', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с высоконагруженными системами', '', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с большими объемами данных', '', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Исправление багов в библиотеках, платформах', '', '11');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Резервное копирование кода', '', '12');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основы систем контроля версий', 'Фиксация изменений, ветвления, отправка и получение данных', '12');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Прочие операции', 'Перемещение и слияние кода, изменение и удаление коммитов, работа с несколькими репозиториями', '12');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Способы совместной работы', 'Централизованная работа, feature branch, gitflow, forking workflow', '12');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с разными системами контроля версий', 'CVS, SVN, Git, Mercurial, Fossil', '12');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Хуки', '', '12');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Интеграция с внешними скриптами', '', '12');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Ручная минификация и оптимизация файлов', '', '13');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Конфигурирование системам сборки', 'Gulp, Grunt, Webpack', '13');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Многовходовая сборка', '', '13');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Нестандартные кофигурации', '', '13');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Сборка legacy-кода', '', '13');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Объединение систем на нескольких фреймворках', '', '13');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с ОС на уровне пользователя', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Установка и удаление программ', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Подключение к сетям', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Консоль', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Консольные команды', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Скрипты', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Конфигурационные файлы/реестр', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с драйверами и оборудованием', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Виртуализация', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Установка ОС', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с ОС на уровне системного администрирования', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Установка и настройка серверных программ', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Организация сетевого взаимодействия', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Архитектура компьютера', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Сетевые коммуникационные протоколы', 'IPv4, IPv6, TCP, UDP, POP, IMAP, SMTP, HTTP, SMB', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Веб-сервер', 'Apache, Nginx, lighthttpd', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('СУБД', 'MySQL, PostgreSQL', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Системы управления конфигурациями', 'Puppet, Chef, Ansible, Salt', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Контейнеризация', 'Vagrant, docker, docker-compose, kubernetes', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('SSH', '', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('VPN', 'OpenVPN, pptpd', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('SSL', 'OpenSSL, Let“s Encrypt', '14');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Хостинг', '', '15');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Amazon', '', '15');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Digital Ocean', '', '15');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Выгрузка при помощи FTP/SFTP', '', '15');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Git', '', '15');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Миграции БД', '', '15');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Системы CI', 'Jenkins, TeamCity, Travis-CI, GitlabCI', '15');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Практики DevOps', 'ChatOps, IaS, Docker, пайплайны', '15');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Системы мониторинга', 'Prometheus, Zabbix', '15');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Kubernetes', '', '15');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Инфраструктурная организация рефакторинга БД', '', '15');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Использование для написания кода', '', '16');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Установка и настройка расширений', '', '16');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Настройка автокоррекции синтаксиса', '', '16');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Функции рефакторинга кода', 'Переименование переменных, функций, классов', '16');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с системой контроля версий', '', '16');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с базой данных', '', '16');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Использование профилировщика', '', '16');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Управляющие комбинации клавиш', '', '16');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Разные IDE', 'IntelliJ IDEA, VS Code, Eclipse', '16');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа в одиночку', '', '17');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа в кроссфункциональной команде', '', '17');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Устранение конфликтов в коде при помощи VCS', '', '17');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Поддержание общего домена знаний', 'Документирование, рассказ о наработках, ответы на вопросы', '17');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Парное программирование', '', '17');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Разработка по каскадной методологии', '', '17');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Гибкие методологии разработки', 'Scrum, kanban', '17');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Организация процесса разработки', '', '17');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа без менеджеров', '', '17');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Принятие решений по собственным ощущениям', '', '18');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Использование данных и фактов для формирования решения', '', '18');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Консультации с коллегами для принятия решения', '', '18');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Навыки безопасной коммуникации', '', '18');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Навыки активного слушания', '', '18');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Использование поисковой системы для поиска решений', '', '19');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Чтение технической литературы', '', '19');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Понимание своих сильных и слабых сторон', '', '19');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Обучение коллег', '', '19');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Подготовка образовательных материалов', '', '19');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Регулярное дистанционное обучение', '', '19');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Регулярное очное обучение', '', '19');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Написание технических статей или записей в блоге', '', '19');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Участие в конференциях в качестве слушателя', '', '19');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Участие в конференциях в качестве докладчика', '', '19');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Поверхностная ревизия', 'По формальным критериям вроде именования, стилистики, местоположения файлов', '20');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Глубокая ревизия кода', 'По всем критериям, включая смысл кода, используемые алгоритмы, соответствие задаче, оптимальность алгоритма и архитектурную корректность', '20');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Позитивная обратная связь по коду', '', '20');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Формирование предложений и идей', 'Чем больше идей, тем лучше', '20');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Ревизия кода в больших задачах', 'Когда кода много', '20');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Использование автоматизированных средств для ревизии', '', '20');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Оценка по собственным ощущениям', '', '21');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Оценка с поправочным коэффициентом', '', '21');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Оценка сроков через сложность задачи', '', '21');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Круговая/коллективная оценка', 'Покер планирования', '21');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Оценка вилкой по двум точкам', 'Минимум, максимум', '21');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Оценка вилкой с тремя точками', 'Минимум, максимум, наиболее вероятный срок', '21');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Скорость команды и диаграмма сгорания', '', '21');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с проектами с небольшим сроком жизни', '', '22');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Переписывание проектов «с нуля»', '', '22');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Предел технической сложности проекта', '', '22');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с техническим долгом', '', '22');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Рефакторинг', '', '22');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с «хрупкими комками грязи»', 'Сложными проектами с хрупким кодом и большим legacy', '22');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Стабилизация скорости разработки проектов', '', '22');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Изучение исходных текстов продуктов', '', '23');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Изучение багтреккеров продуктов', '', '23');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Оформление PRов к продуктам с открытым кодом', '', '23');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Решение PRов, подготовка пулл-запросов', '', '23');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Постоянная поддержка проекта с открытым кодом', '', '23');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Участие в Open Source сообществах', '', '23');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Знание иностранного языка на уровне чтения документации', 'Beginner, Elementary, Pre-Intermediate', '24');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Знание на уровне полноценного письменного общения', 'Intermediate, Upper-Intermediate', '24');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Понимание устной речи', '', '24');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Поддержка разговоров на технические темы', '', '24');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Поддержка разговоров на бытовые темы', '', '24');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Деловая и техническая переписка', '', '24');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Знание на уровне свободного владения языка', 'Advanced, Proficiency', '24');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Сертификация знаний иностранного языка', 'TOEFL, IELTS', '24');


INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Размещения, перестановки, сочетания', '', '27');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Биномиальные коэффициенты', '', '27');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Математическое ожидание', '', '27');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Дисперсия', '', '27');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Условная вероятность', '', '27');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основные распределения', 'Нормальное, биномиальное, Стьюдента, Пуассона, Трейси-Видома', '27');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основные понятия', 'Тест-план, Тест-кейс, баг', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Эффект пестицида', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с багтреккером', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с функциональными требованиями', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Классы эквивалентности', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Формирование разбиения области тестирования', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Анализ границ области тестирования', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Методики тестирования', 'Черный, белый и серый ящики', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Виды тестирования', 'Компонентное, системное, интеграционное. Регрессионное, стресс, приёмочное', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Построение тест-плана', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Построение тест-кейсов', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Причинно-следственные диаграммы', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Анализ модели состояния', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Оценка покрытия кода и требований тестами', 'Покрытие функций, условий, решений', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Основные понятия веб-разработки', 'Веб-сервер, веб-клиент, POST-запросы, GET-запросы', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Использование средств перехвата запросов', 'Fiddler', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Протоколы веб', 'HTTP, JSON, FTP, telnet, SMTP, POP', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Тестирование защищенности веб-приложений', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('SQL-инъекции', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('XSS', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Нагрузочное тестирование', 'JMeter, HP Load Runner, ab, siege', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Сборка динамического покрытия кода тестами', '', '28');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Знание языка программирования', 'Python, java, javascript, C#', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Использование IDE', '', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Инструменты записи сценариев', '', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Инспекция кода', '', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Тест-дизайн', '', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Средства отладки в CLI и IDE', '', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Использование Selenium', 'или надстроек Appium, Winium, Windows Application Driver', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Data Driven Testing', '', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Behaviour Driven Testing', '', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Model Driven Testing', '', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Keyword Driven Testing', '', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Шаблоны проектирования тестов', 'Functional, PageObjects', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Распределенное тестирование', '', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Selenium Server', '', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Selenium Grid', '', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Облачные сервисы тестирования', '', '29');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Встроенные типы переменных', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Mutable/immutable типы', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Динамическая типизация', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Базовый синтаксис языка', 'И инструкции управления потоком выполнения', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Синтаксис функций', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Области видимости переменных', 'Правило LEGB', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Итераторы', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Генераторы', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Документирование кода', 'В соответствии с PEP8', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Средства функционального программирования', 'map, filter, reduce', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Анонимные функции (lambda)', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Использование инструкции yield', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Проектирование модулей', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Работа с модулями', 'Повторная загрузка, относительный импорт, сокрытие данных', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Классы, создание и использование', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Наследование и переопределение методов', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Композиция и делегирование для классов', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Перегрузка операторов', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Фабрики объектов', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Классы "старого" и "нового" стилей', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Создание и использование исключений', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Создание и использование контекстных менеджеров', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Объекты unicode, bytes, bytearray', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Env-сборки', 'При помощи утилиты pip', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Консольный отладчик python', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Декораторы функций', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Декораторы классов', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Дескрипторы', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Множественное наследование', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Различные варианты python', 'cpython, ironpython, jpython, Stackless Python', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Разработка с веб-фреймворками', 'Django, Flask, Pyramid', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Разработка с GUI-фреймворками', 'PyQt, Tkinter, WxPython', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Метапрограммирование', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Сетевое программирование', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Асинхронное программирование', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Мультипроцессное программирование', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Мультипоточное программирование', '', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('Специализированные библиотеки', 'NumPy, SciPy, SQLAlchemy', '26');
INSERT INTO `atomicSkills` (`text`, `additionalDescription`, `competencyId`) VALUES ('«Великодушный пожизненный диктатор»', '', '26');


