ALTER TABLE `polls` ADD COLUMN `sessionId` VARCHAR(36) DEFAULT NULL AFTER `userId`;

ALTER TABLE courses ADD COLUMN modeOfStudy VARCHAR(20) DEFAULT NULL NULL;
ALTER TABLE courses ADD COLUMN courseForm VARCHAR(20) DEFAULT NULL NULL;
ALTER TABLE courses ADD COLUMN `schedule` VARCHAR(20) DEFAULT NULL NULL;
ALTER TABLE courses ADD COLUMN certificate INT(1) DEFAULT 0 NOT NULL;
ALTER TABLE courses ADD COLUMN tasksType VARCHAR(20) DEFAULT NULL  NULL;
ALTER TABLE courses ADD COLUMN lengthDays INT DEFAULT 0 NULL;
ALTER TABLE courses ADD COLUMN eduProviderId INT DEFAULT NULL NULL AFTER id;
ALTER TABLE courses ADD COLUMN externalId VARCHAR(36) DEFAULT NULL NULL AFTER id;
ALTER TABLE courses ADD COLUMN `description` TEXT NULL DEFAULT NULL AFTER `name`;
