version: "2"

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - "./public:/var/www/public"
      - "./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php

  php:
    image: php:7.1-fpm
    build:
      context: "."
      dockerfile: "./etc/php/Dockerfile"
    working_dir: "/var/www"
    environment:
      - MYSQL_DSN=${PDO_DSN}
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - API_URL=${API_URL}
      - MAILGUN_KEY=${MAILGUN_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - XDEBUG_CONFIG=remote_host=${HOST_IP}

    volumes:
      - ".:/var/www"
      - "./etc/php/log-stdout.conf:/usr/local/etc/php-fpm.d/zz-log.conf"
      - "./etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
      - "./etc/php/pdo_sqlite.ini:/usr/local/etc/php/conf.d/pdo_sqlite.ini"
    depends_on:
      - database

  database:
    image: mariadb
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_SCHEMA}
    volumes:
      - "./etc/database/data:/var/lib/mysql"
      - "./etc/database:/docker-entrypoint-initdb.d"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
