version: "2"

services:
  nginx:
    image: nginx
    ports:
      - 8090:80
    volumes:
      - "./public:/var/www/public"
      - "./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php

  php:
    image: php:7.3-fpm
    build:
      context: "."
      dockerfile: "./etc/php/Dockerfile"
    working_dir: "/var/www"
    environment:
      - MYSQL_DSN=${PDO_DSN}
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - API_URL=${API_URL}
      - MAILGUN_KEY=${MAILGUN_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - XDEBUG_CONFIG=remote_host=${HOST_IP}
      - MONGO_HOST=mongo
      - MONGO_DB=skillitch

    volumes:
      - ".:/var/www"
      - "./etc/php/log-stdout.conf:/usr/local/etc/php-fpm.d/zz-log.conf"
      - "./etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
      - "./etc/php/pdo_sqlite.ini:/usr/local/etc/php/conf.d/pdo_sqlite.ini"
    depends_on:
      - database
      - mongo

  database:
    image: mariadb
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_SCHEMA}
    volumes:
      - "./etc/database/data:/var/lib/mysql"
      - "./etc/database:/docker-entrypoint-initdb.d"

  mongo:
    image: mongo
    volumes:
      - ./etc/database/mongo:/data/db
    restart: always
    ports:
      - 27117:27017