#!/usr/bin/env php
<?php

use Competencies\Command\ParseConfig;
use Webmozart\Console\ConsoleApplication;

require_once ('vendor/autoload.php');

function setupEnvironment() {
    if (file_exists('.env')) {
        $envVars = explode("\n", file_get_contents('.env'));
        foreach ($envVars as $envVar) {
            putenv($envVar);
        }
    }
}

setupEnvironment();
$cli = new ConsoleApplication(new ParseConfig());
$cli->run();

